class QuizSubject {
  final String id;
  final String title;
  final String subtitle;
  final String description;
  final int totalQuestions;
  final int itemsPerSection;
  final int totalSections;
  final String badgeText;
  final String iconType;
  final String category; // 'bped', 'gen_ed', 'prof_ed'

  const QuizSubject({
    required this.id,
    required this.title,
    required this.subtitle,
    required this.description,
    required this.totalQuestions,
    required this.itemsPerSection,
    required this.totalSections,
    required this.badgeText,
    required this.iconType,
    required this.category,
  });

  static const List<QuizSubject> availableSubjects = [
    QuizSubject(
      id: 'bped_quiz',
      title: 'BPED Major Specialization',
      subtitle: 'Physical Education Drills',
      description: 'Physical Education, Movement Science, Sports Ethics, Rhythmics & Health Education licensure questions.',
      totalQuestions: 150,
      itemsPerSection: 50,
      totalSections: 3,
      badgeText: '3 SECTIONS • 50 ITEMS EACH',
      iconType: 'bped',
      category: 'bped',
    ),
    QuizSubject(
      id: 'bped_practice_test',
      title: 'BPED Majorship Practice Test',
      subtitle: '100 Practice Test Questions',
      description: 'Falculan Twins Review Center BPED Majorship practice test covering physical education, sports, health, and anatomy with answer key.',
      totalQuestions: 100,
      itemsPerSection: 50,
      totalSections: 2,
      badgeText: '2 SECTIONS • 100 ITEMS',
      iconType: 'bped',
      category: 'bped',
    ),
    QuizSubject(
      id: 'bped_matatag_curriculum',
      title: 'BPED MATATAG Curriculum Drill 1',
      subtitle: '150 Items MATATAG PE & Health',
      description: '150 MATATAG Curriculum drill questions covering BPED, PE & Health learning area standards, DBAE, and pedagogy.',
      totalQuestions: 150,
      itemsPerSection: 50,
      totalSections: 3,
      badgeText: '3 SECTIONS • 150 ITEMS',
      iconType: 'bped',
      category: 'bped',
    ),
    QuizSubject(
      id: 'prof_ed_spec_drill_2',
      title: 'BPED Specialization Drill 2',
      subtitle: '150 Items Specialization Mock Test',
      description: 'BPED Specialization Drill 2 Mock Test covering physical education, sports, health, anatomy, research, and pedagogy.',
      totalQuestions: 150,
      itemsPerSection: 50,
      totalSections: 3,
      badgeText: '3 SECTIONS • 150 ITEMS',
      iconType: 'bped',
      category: 'bped',
    ),
    QuizSubject(
      id: 'bped_spec_drill_3',
      title: 'BPED Specialization Drill 3',
      subtitle: '150 Items Sports P1 Drill',
      description: 'BPED Specialization Drill 3 Sports P1 covering Football, Basketball, Volleyball, Baseball, Softball, Badminton, Table Tennis, Tennis, and Athletics.',
      totalQuestions: 150,
      itemsPerSection: 50,
      totalSections: 3,
      badgeText: '3 SECTIONS • 150 ITEMS',
      iconType: 'bped',
      category: 'bped',
    ),
    QuizSubject(
      id: 'bped_spec_drill_4',
      title: 'BPED Specialization Drill 4',
      subtitle: '150 Items Sports P2 Drill',
      description: 'BPED Specialization Drill 4 Sports P2 covering Philippine Traditional Games, Swimming, Aquatics, Taekwondo, Arnis, Sepak Takraw, and Biomechanics.',
      totalQuestions: 150,
      itemsPerSection: 50,
      totalSections: 3,
      badgeText: '3 SECTIONS • 150 ITEMS',
      iconType: 'bped',
      category: 'bped',
    ),
    QuizSubject(
      id: 'bped_ppst_drill_8',
      title: 'BPED PPST Drill 8 Set A',
      subtitle: '150 Items PPST Standards Drill',
      description: 'BPED PPST Drill 8 Set A covering PE Curriculum, Motor Development, Biomechanics, Exercise Physiology, Pedagogy, and Assessment.',
      totalQuestions: 150,
      itemsPerSection: 50,
      totalSections: 3,
      badgeText: '3 SECTIONS • 150 ITEMS',
      iconType: 'bped',
      category: 'bped',
    ),
    QuizSubject(
      id: 'bped_ppst_drill_9',
      title: 'BPED PPST Drill 9 Set B',
      subtitle: '150 Items PPST Standards Drill',
      description: 'BPED PPST Drill 9 Set B covering PE Curriculum, Differentiated Instruction, Biomechanics, Inclusive Education, and Motor Skill Learning.',
      totalQuestions: 150,
      itemsPerSection: 50,
      totalSections: 3,
      badgeText: '3 SECTIONS • 150 ITEMS',
      iconType: 'bped',
      category: 'bped',
    ),
    QuizSubject(
      id: 'bped_mock_test_1',
      title: 'BPED Specialization Mock Test 1',
      subtitle: '150 Items Mock Examination',
      description: 'BPED Specialization Mock Test 1 covering Kinesiology, Biomechanics, Exercise Physiology, Motor Learning, Sports Officiating, and Philippine Folk Dance.',
      totalQuestions: 150,
      itemsPerSection: 50,
      totalSections: 3,
      badgeText: '3 SECTIONS • 150 ITEMS',
      iconType: 'bped',
      category: 'bped',
    ),
    QuizSubject(
      id: 'bped_mapeh_part_6',
      title: 'MAPEH Part 6 Reviewer',
      subtitle: '50 Items Sports & Folk Dance',
      description: 'MAPEH Part 6 reviewer covering Basketball, Football, Gymnastics, Sports Aerobics, and Philippine Folk Dances.',
      totalQuestions: 50,
      itemsPerSection: 50,
      totalSections: 1,
      badgeText: '1 SECTION • 50 ITEMS',
      iconType: 'bped',
      category: 'bped',
    ),
    QuizSubject(
      id: 'bped_cbrc_mapeh',
      title: 'CBRC Analytical MAPEH Coaching',
      subtitle: '150 Items PE, Health, Music & Arts',
      description: 'CBRC Analytical MAPEH Final Coaching reviewer covering physical education, sports, health, music theory, and fine arts.',
      totalQuestions: 150,
      itemsPerSection: 50,
      totalSections: 3,
      badgeText: '3 SECTIONS • 150 ITEMS',
      iconType: 'bped',
      category: 'bped',
    ),
    QuizSubject(
      id: 'bped_ftrc_health',
      title: 'FTRC Health Practice Test Set',
      subtitle: '60 Items Health & First Aid',
      description: 'FTRC Health practice test covering First Aid, Emergency Care, Infectious Diseases, Substance Abuse, and Health Education.',
      totalQuestions: 60,
      itemsPerSection: 50,
      totalSections: 2,
      badgeText: '2 SECTIONS • 60 ITEMS',
      iconType: 'bped',
      category: 'bped',
    ),
    QuizSubject(
      id: 'bped_ftrc_mapeh_set_a_b',
      title: 'FTRC MAPEH Practice Test Set A & B',
      subtitle: '100 Items Dance, Olympics & Arts',
      description: 'Falculan Twins Review Center MAPEH Practice Test Set A & B covering folk dances, rhythmic movements, Olympics history, research, and fine arts.',
      totalQuestions: 100,
      itemsPerSection: 50,
      totalSections: 2,
      badgeText: '2 SECTIONS • 100 ITEMS',
      iconType: 'bped',
      category: 'bped',
    ),
    QuizSubject(
      id: 'bped_traditional_games',
      title: 'Philippine Traditional Games',
      subtitle: '25 Items Laro ng Lahi Drill',
      description: '25-item practice test on Philippine Traditional Games (Patintero, Palo Sebo, Sungka, Pukpok Palayok, Luksong Tinik, Luksong Baka, etc.).',
      totalQuestions: 25,
      itemsPerSection: 25,
      totalSections: 1,
      badgeText: '1 SECTION • 25 ITEMS',
      iconType: 'bped',
      category: 'bped',
    ),
    QuizSubject(
      id: 'bped_pedagogy_mapeh',
      title: 'Pedagogy in MAPEH Practice Test',
      subtitle: '100 Items Teaching & Assessment',
      description: 'Falculan Twins Review Center 100-item practice test on Pedagogy, Art/PE Principles, Assessment, and Classroom Management.',
      totalQuestions: 100,
      itemsPerSection: 50,
      totalSections: 2,
      badgeText: '2 SECTIONS • 100 ITEMS',
      iconType: 'bped',
      category: 'bped',
    ),
    QuizSubject(
      id: 'bped_health_anatomy',
      title: 'Health and Anatomy Reviewer',
      subtitle: '70 Items Anatomy & Kinesiology',
      description: 'Falculan Twins Review Center 70-item drill on Skeletal System, Muscular System, Kinesiology, Circulatory & Nervous Systems, and Organ Functions.',
      totalQuestions: 70,
      itemsPerSection: 50,
      totalSections: 2,
      badgeText: '2 SECTIONS • 70 ITEMS',
      iconType: 'bped',
      category: 'bped',
    ),
    QuizSubject(
      id: 'gen_ed',
      title: 'General Education',
      subtitle: '1,000 Items Reviewer',
      description: 'Comprehensive General Education questions covering English, Filipino, Math, Science, and Social Science.',
      totalQuestions: 1000,
      itemsPerSection: 50,
      totalSections: 20,
      badgeText: '20 SECTIONS • 50 ITEMS EACH',
      iconType: 'gen_ed',
      category: 'gen_ed',
    ),
    QuizSubject(
      id: 'gen_ed_2026_set_a',
      title: 'General Education 2026',
      subtitle: '148 Items March 2026 Set A',
      description: 'Official March 15, 2026 Secondary Licensure Examination General Education Set A with answer key.',
      totalQuestions: 148,
      itemsPerSection: 50,
      totalSections: 3,
      badgeText: '3 SECTIONS • 148 ITEMS',
      iconType: 'gen_ed',
      category: 'gen_ed',
    ),
    QuizSubject(
      id: 'gen_ed_rizal_math',
      title: 'Rizal & General Mathematics',
      subtitle: '115 Actual LET Questions',
      description: 'Life & Works of Rizal (50 Items) and General Mathematics (65 Items) actual licensure board exam questions with rationalizations.',
      totalQuestions: 115,
      itemsPerSection: 50,
      totalSections: 3,
      badgeText: '3 SECTIONS • 115 ITEMS',
      iconType: 'gen_ed',
      category: 'gen_ed',
    ),
    QuizSubject(
      id: 'gen_ed_qa',
      title: 'General Education QA',
      subtitle: '50 Items Gen Ed Review',
      description: 'General Education QA covering English, Filipino, Social Science, Philippine History, Literature (Filipino & World), and Science.',
      totalQuestions: 50,
      itemsPerSection: 50,
      totalSections: 1,
      badgeText: '1 SECTION • 50 ITEMS',
      iconType: 'gen_ed',
      category: 'gen_ed',
    ),
    QuizSubject(
      id: 'gen_ed_pabaon_2024',
      title: 'General Education High-Yield Pabaon',
      subtitle: '150 Essential Key Concepts',
      description: 'Comprehensive 2024 LET General Education Pabaon covering English, Filipino, Science, History, Politics, and Art.',
      totalQuestions: 150,
      itemsPerSection: 50,
      totalSections: 3,
      badgeText: '3 SECTIONS • 150 ITEMS',
      iconType: 'gen_ed',
      category: 'gen_ed',
    ),
    QuizSubject(
      id: 'prof_ed_150',
      title: 'Professional Education',
      subtitle: '150 Items Mock Exam',
      description: 'Official 150-Item Professional Education Secondary Licensure Examination Set A with answer key.',
      totalQuestions: 150,
      itemsPerSection: 50,
      totalSections: 3,
      badgeText: '3 SECTIONS • 50 ITEMS EACH',
      iconType: 'prof_150',
      category: 'prof_ed',
    ),
    QuizSubject(
      id: 'prof_ed_1000',
      title: 'Professional Education',
      subtitle: '1,000 Practice Drills',
      description: '2024 Edition Kaguro LET Publishing 1,000 actual Professional Education questions and concepts.',
      totalQuestions: 1000,
      itemsPerSection: 50,
      totalSections: 20,
      badgeText: '20 SECTIONS • 50 ITEMS EACH',
      iconType: 'prof_1000',
      category: 'prof_ed',
    ),
    QuizSubject(
      id: 'prof_ed_pabaon_2024',
      title: 'Professional Education High-Yield Pabaon',
      subtitle: '75 Core Teaching Concepts',
      description: 'September 2024 Edition Professional Education final review key concepts, pedagogical theories, and scenarios.',
      totalQuestions: 75,
      itemsPerSection: 25,
      totalSections: 3,
      badgeText: '3 SECTIONS • 75 ITEMS',
      iconType: 'prof_150',
      category: 'prof_ed',
    ),
    QuizSubject(
      id: 'prof_ed_2026_set_a',
      title: 'Professional Education 2026',
      subtitle: '150 Items March 2026 Set A',
      description: 'Official March 15, 2026 Secondary Licensure Examination Professional Education Set A with answers and explanations.',
      totalQuestions: 150,
      itemsPerSection: 50,
      totalSections: 3,
      badgeText: '3 SECTIONS • 150 ITEMS',
      iconType: 'prof_150',
      category: 'prof_ed',
    ),
    QuizSubject(
      id: 'prof_ed_official_set_a',
      title: 'Prof Ed Official Test Booklet Set A',
      subtitle: '150 Items Licensure Exam',
      description: 'Official Secondary Licensure Examination Professional Education Set A test booklet with answer keys.',
      totalQuestions: 150,
      itemsPerSection: 50,
      totalSections: 3,
      badgeText: '3 SECTIONS • 150 ITEMS',
      iconType: 'prof_150',
      category: 'prof_ed',
    ),
    QuizSubject(
      id: 'prof_ed_2026_set_b',
      title: 'Professional Education 2026 Set B',
      subtitle: '150 Items March 2026 Set B',
      description: 'Official March 15, 2026 Secondary Licensure Examination Professional Education Set B with verified answer keys.',
      totalQuestions: 150,
      itemsPerSection: 50,
      totalSections: 3,
      badgeText: '3 SECTIONS • 150 ITEMS',
      iconType: 'prof_150',
      category: 'prof_ed',
    ),
  ];

  static QuizSubject getById(String id) {
    return availableSubjects.firstWhere(
      (s) => s.id == id,
      orElse: () => availableSubjects.first,
    );
  }

  static List<QuizSubject> getByCategory(String category) {
    return availableSubjects.where((s) => s.category == category).toList();
  }
}
