// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwZQBWPJdOC5SLb9fGWQYboA3314MPvLQ',
    appId: '1:404491804324:web:1980cb80eae0a88e009031',
    messagingSenderId: '404491804324',
    projectId: 'lets-94d73',
    authDomain: 'lets-94d73.firebaseapp.com',
    storageBucket: 'lets-94d73.firebasestorage.app',
    measurementId: 'G-2HQHYJK3BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj2pI5eRk78IlNM6WBmUIsDU0-nX3Dxd0',
    appId: '1:404491804324:android:5d7854ee60186822009031',
    messagingSenderId: '404491804324',
    projectId: 'lets-94d73',
    storageBucket: 'lets-94d73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ7dMosmCpCUyDD2gqcnqbRmlEczlJHpo',
    appId: '1:404491804324:ios:3e12eb7cd09468ff009031',
    messagingSenderId: '404491804324',
    projectId: 'lets-94d73',
    storageBucket: 'lets-94d73.firebasestorage.app',
    iosBundleId: 'com.example.topnotcherYarn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ7dMosmCpCUyDD2gqcnqbRmlEczlJHpo',
    appId: '1:404491804324:ios:3e12eb7cd09468ff009031',
    messagingSenderId: '404491804324',
    projectId: 'lets-94d73',
    storageBucket: 'lets-94d73.firebasestorage.app',
    iosBundleId: 'com.example.topnotcherYarn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwZQBWPJdOC5SLb9fGWQYboA3314MPvLQ',
    appId: '1:404491804324:web:2f39e491f394281c009031',
    messagingSenderId: '404491804324',
    projectId: 'lets-94d73',
    authDomain: 'lets-94d73.firebaseapp.com',
    storageBucket: 'lets-94d73.firebasestorage.app',
    measurementId: 'G-6R1W82HT1H',
  );
}
