import os
import json

# Complete list of 150 questions for BPED PPST Drill 8 Set A
raw_items = [
    # --- Section 1 (Q1 to Q50) ---
    ("The players are moving around defenders and keep an eye on their teammates' positions on the court as they practice passing during a basketball practice. In this sporting context, which of the following movement concepts relates to relationships?", ["How hard the movement is", "Speed of how fast the movement occurs", "Movement concerning another player", "Movement in one direction"], 2),
    ("To increase their muscular endurance for better sports performance and daily activities, a group of teenagers is creating a weekly fitness program. Which training regimen is best for assisting them in developing muscular endurance?", ["Performing 3 repetitions with maximum weight during each set", "Engaging in 30-minute circuit training sessions involving light-to moderate resistance and minimal rest between exercises", "Sprinting 100 meters, followed by a brief rest, and repeating the cycle", "Performing a one-repetition maximum (1 RM) squat to test peak strength weekly"], 1),
    ("A Physical Education teacher in grade four intends to evaluate her students development of motor skills like throwing, hopping, and skipping. She is looking for an evaluation tool that will give her unbiased, thorough, and consistent feedback on each student's performance. Which evaluation instrument best suits her objective?", ["Anecdotal records only", "Written tests on health topics", "Performance rubrics with clear skill criteria", "Posting hygiene practices clearly on the board for student visibility and reminders."], 2),
    ("When combining skipping with music in dance, which skills are being integrated?", ["Non-locomotor and static", "Locomotor and rhythmic", "Static and manipulative", "Balance and endurance"], 1),
    ("Coach Valencia teaches novice basketball players a new dribbling technique during practice. She observes that the majority of them are paying close attention, making mistakes frequently, and seeking clarification on how to execute the movement correctly. Which stage of the players' motor skill development are they most likely in?", ["Associative", "Cognitive", "Autonomous", "Kinesthetic"], 1),
    ("A family fitness program is started by a Physical Education teacher who encourages students to participate in regular physical activities with their family members. Given their hectic schedules, many parents wonder if such a program is really necessary. It is your responsibility as a student leader to provide the strongest argument for backing the project. Which of the following explanations best advances the goal of this regular family activity?", ["To win local competitions", "To foster consistent role modeling and shared routines", "To replace academic assignments and any practical activities", "To track daily calorie intake"], 1),
    ("A number of the university track team's sprinters have suffered from recurrent hamstring injuries during explosive sprints, according to coach Reyes. He examines sports science-based injury prevention techniques to address this problem. Which tactic from the list below should Coach Reyes use to put the idea of avoiding non-contact muscle injuries like hamstring tears into practice?", ["Use static stretching before training", "Gradually increase sprint distance each training day.", "Decrease water intake before running", "Implement eccentric strengthening exercises"], 3),
    ("A teacher wants to maintain assessment value while incorporating active participation and variety to assess students' skill development entertainingly and engagingly. Which approach, rather than depending only on passive or repetitive techniques, best blends skill demonstration, motivation, and enjoyment to make learning dynamic and meaningful?", ["Skill challenge circuit", "Written test", "Repetitive movement exercises to improve skill execution.", "Homework"], 0),
    ("A Physical Education instructor is organizing movement exercises for students in various grade levels. The teacher looks at how middle childhood students perform jump rope routines and how preschoolers react to hopping games to make sure it is developmentally appropriate. In early childhood Physical Education, which teacher's choice best illustrates the analysis of age-appropriate activities?", ["Assigning students to run laps around the gym", "Introducing yoga poses that require balance and control", "Teaching complex basketball plays enhances teamwork development.", "Comparing gross motor activities: preschoolers vs. middle childhood."], 3),
    ("Following the implementation of a six-week customized fitness program aimed at improving muscular strength and cardiovascular endurance by a senior high school student, the P.E. A follow-up assessment was conducted by the teacher. The instructor observed that the student had recently purchased new exercise equipment, regularly shared fitness updates on social media, and consistently attended training sessions. However, the post-assessment results revealed a notable increase in push-up repetitions and a 25% improvement in the student’s 3-minute step test. Which metric best assesses the success of the student's customized plan in light of these findings?", ["Purchase of fitness gear and training materials", "Number of social media fitness posts", "Number of gym attendance stamps", "Improved scores in post-fitness assessments"], 3),
    ("Which set of elements most accurately describes why certain students find it difficult to grasp challenging movement tasks?", ["Genetics and equipment quality", "Learning style and peer influence", "Instructional method and anxiety", "Motivation and class schedule"], 2),
    ("A high school coach observes during a training session that one of his sprinters frequently has hamstring pain and tightness following short-distance sprints. After examining the athlete's running technique, the coach believes there may be a biomechanical limitation that is impaining performance and raising the risk of injury. In order to help prevent more hamstring tightness, which of the following biomechanical issues should the coach address?", ["Limited hip extension", "Shoulder imbalance", "Tight gastrocnemius", "Weak triceps"], 0),
    ("Why is it crucial to assess whether health education's content is current and appropriate for a given culture?", ["To follow the textbook strictly as mandated by the Department of Education", "To ensure the material is easy enough for all students to pass exams", "To avoid topics that may be too sensitive for some students", "To deliver meaningful health information for learners"], 3),
    ("When making abrupt direction changes during varsity basketball practice, a player usually rolls his ankle. In order to find any functional deficiencies or imbalances that might be causing the recurrent injury, the coach wants to evaluate the athlete's movement patterns. Which screening instrument ought to be employed by the coach to assess the risk factors of the athlete?", ["Resting heart rate monitor", "Blood sugar test", "Functional movement screen (FMS)", "VO2 max test"], 2),
    ("What conclusions can be made by examining the variations between students' pre- and post-fitness test results?", ["Identify students' favorite physical activities", "Determine the effectiveness of the fitness program", "Assess students' interest in sports", "Measure daily attendance rates"], 1),
    ("Skipping is best described as a combination of which two skills?", ["Walking and stretching", "Hopping and jumping", "Walking and hopping", "Running and twisting"], 2),
    ("A client of a fitness trainer is working to increase muscle strength. Which of the following tactics should the trainer use to adhere to the overload principle and guarantee ongoing physical improvement?", ["Reduce the workout time to avoid fatigue", "Skip rest days to keep the intensity up", "Maintain the same routine to ensure consistency", "Increase the weight lifted or number of repetitions performed"], 3),
    ("What skill involves moving in place without traveling?", ["Running", "Dribbling", "Stretching", "Skipping"], 2),
    ("In a group Physical Education class, a student with asthma is taking part. Which of the following best describes what the instructor should do to protect the student and encourage involvement?", ["Require the student to perform full activities without modifications to promote equal treatment.", "Allow the student to sit out and take a written quiz instead of participating.", "Adjust the activity by reducing intensity or duration based on the student's condition.", "Have the student lead warm-up exercises and then supervise the rest of the class to avoid physical strain."], 2),
    ("A checklist in evaluating a skill performance is an example of?", ["feedback", "video analysis", "rubric tool", "self-assessment"], 2),
    ("This movement pattern may suggest weakness in particular muscle groups, which, if left untreated, could result in long-term physical problems. What biomechanical issue is raised when students jump and land with their knees collapsing inward?", ["Balance", "Correct posture boosts confidence", "Injury risk due to valgus collapse", "Heart rate"], 2),
    ("Your task is to create a Physical Education exercise for a class of students with diverse skill levels and abilities. Which of the following strategies would most effectively implement the idea of inclusive education to guarantee that every student participates and engages equally?", ["Grouping students into mixed-level teams to promote cooperation and peer learning", "Selecting only the most skilled athletes to participate in competitive drills", "Implementing the same drill routine for all students regardless of ability", "Removing team activities entirely to avoid differences in skill level"], 0),
    ("Why might a teenager perform better than a child in motor skills related to balance during Physical Education exercises?", ["They have better reflex responses.", "They receive more instruction.", "They are in the associative stage of learning.", "Advanced neuromuscular development"], 3),
    ("Which of the following is a locomotor skill?", ["Twisting", "Jumping", "Stretching", "Bending"], 1),
    ("It is your responsibility to evaluate a group of kindergarteners' level of physical fitness. Their coordination and balance are among the things you need to assess. Which of the following exercises would be best suited to evaluate a child's practical balancing skills?", ["Administering a multiple-choice quiz on balance concepts", "Conducting a beep test to measure cardiovascular endurance", "Asking the child to stand on one foot for a specific time", "Having the child read a paragraph aloud in front of the class"], 2),
    ("A student is practicing shooting a basketball. They often miss the hoop in the beginning. They start to show more consistency after a few sessions and modify their form in response to criticism. In a Physical Education lesson, how would you demonstrate the acquisition of associative stage skills?", ["Flawed and unsure", "Fast and automatic", "Slow but refining", "Completely new to the task"], 2),
    ("What does cardiovascular endurance indicate about a person?", ["Force muscles can produce.", "Heart and lung health", "Bone flexibility", "Agility level"], 1),
    ("What is the best connection to make when utilizing a concept map to illustrate the development of motor skills in young children?", ["Crawling linked with puberty", "Running linked with abstract reasoning", "Fine motor aids pre-writing.", "Jumping linked with social identity"], 2),
    ("Promoting fitness practices that improve health in a diverse neighborhood with little access to gyms or other official exercise facilities is your mission. Which innovative approach has the best chance of inspiring broad participation and encouraging sustained physical activity when taking reach, engagement, and sustainability into account?", ["Record weight lifting sessions", "Use a heart rate app to monitor running zones", "Store stretching videos on a flash drive", "Watch sports highlight reels to enhance knowledge of physical activities"], 1),
    ("Despite having a good warm-up and diet before the match, a coach observes that one of her players starts to exhibit symptoms of arm fatigue by the third set of a high-intensity volleyball match. The player finds it difficult to keep her spikes and blocks accurate and powerful. Which short-term physiological adjustment is most likely failing, causing her to become fatigued early, given the physiological demands of repeated explosive actions?", ["Fast-twitch fiber activation", "Lactate threshold buffering", "Muscle glycogen storage", "Oxygen absorption in the lungs"], 1),
    ("What makes a fine motor skill different from a gross motor skill?", ["Gross motor skill uses fewer muscles while fine motor skill uses larger muscles.", "GMS allows the body to move from one place to another while GMS allows the body to move in a stationary position.", "Gross uses larger muscle groups while fine motor skill uses small muscle groups.", "Fine requires no control while gross with control."], 2),
    ("To improve her Grade 2 students' overall athleticism, a Physical Education teacher is creating a weekly training schedule. Her goal is to help the kids improve their fundamental movement skills (FMS) so they can play a variety of sports in the future. Which set of activities should she prioritize in the light of their developmental needs?", ["Only balance drills", "Throwing, catching, running", "Memory games and flashcards", "Isolated muscle hypertrophy workouts"], 1),
    ("Which muscle type controls involuntary movements like blood vessel regulation and digestion?", ["Smooth muscle", "Skeletal muscle", "Cardiac muscle", "Flexor muscle"], 0),
    ("A Physical Education teacher notices that certain students exhibit symptoms of stress and anxiety during a planning session. The instructor chooses to update the curriculum in response. Which of the following activities best illustrates how health topics are incorporated into Physical Education?", ["Providing brochures about hygiene", "Evaluating how mental health is supported through team sports", "Showing a video on exercise", "Displaying hygiene practices clearly on the board for students to follow"], 1),
    ("What is the best reason to incorporate mental health into the Enhanced Basic Education Program's Health Education curriculum?", ["To follow the international trend of discussing psychological topics in schools", "To fill extra class time with non-academic discussions", "To support students' emotional well-being as part of holistic development", "To reduce the workload of guidance counselors"], 2),
    ("A year-long progressive Physical Education (PE) program was introduced at a high school with the goal of raising student motivation and fitness engagement. The school hopes to determine at the end of the year whether the program changed the way students engage in and perform in Physical Education classes. Which approach offers the most suitable and thorough assessment of the program's efficacy?", ["Analyzing self-assessment performance trends", "Observing class attendance", "Measuring BMI annually", "Asking parents about physical activity at home"], 0),
    ("Four students were asked to create personal fitness goals based on their results from the individual fitness tests they took in Physical Education class. The SMART goal-setting framework-Specific, Measurable, Achievable, Relevant, and Time-bound —is crucial for creating goals that encourage accountability and personal growth, according to their Physical Education instructor. Objective Statements: Maria: \"One day, I hope to run ten kilometers.\" Jon: \"By the end of the year, I want to be healthier.\" Ella: \"In the next six weeks, I want to cut 30 seconds off my one-mile run time.\" Mark: \"I just want to do more workouts whenever I can,\" Which student, following the fitness evaluation, best applies the framework based on the SMART goal setting principles?", ["Maria aims to run 10 km someday.", "Jon wants to be \"healthier\" within the year.", "Ella plans to improve her mile time by 30 seconds in 6 weeks.", "Mark sets a vague goal to \"do more workouts.\" Within 20 min to 30 minutes."], 2),
    ("Which school of thought stresses the value of Physical Education in fostering the growth of moral and intellectual character via structure and discipline?", ["Naturalism", "Existentialism", "Pragmatism", "Idealism"], 3),
    ("Which of the following best sums up how the Enhanced Basic Education Program incorporates values like critical thinking and teamwork into Physical Education?", ["To make PE classes more enjoyable and engaging", "To prepare students for competitive sports dealing with sports activities", "To support holistic development in line with 21st-century competencies", "To reduce the time spent on traditional fitness tests"], 2),
    ("What best defines muscular strength as opposed to muscular endurance?", ["It measures how long you can sustain an activity.", "It focuses on heart and lung efficiency.", "It involves the ability to exert force.", "It enhances flexibility and range of motion."], 2),
    ("While looking over preseason injury reports as the assistant coach of a university swim team, you notice that several athletes have strained their shoulders. You remember how their training sessions have been more intense lately, with a greater emphasis on drills involving the freestyle and butterfly strokes, with little change in movement patterns. Which of the following risk factors is most likely to be causing these shoulder injuries, given the circumstances?", ["Repetitive overhead motion overuse", "Inadequate sun exposure", "Lack of rest days", "Too much legwork in training"], 0),
    ("In a Physical Education class, the instructor adapts stretching exercises by adding upper-body movements and giving a student in a wheelchair resistance bands during a warm-up. The instructor makes sure the student is participating and working out with their peers. Which educational approach is best illustrated by this scenario?", ["Standardized assessment", "Adaptive Physical Education", "Peer mentoring", "Group evaluation"], 1),
    ("The ball is thrown from the outfield to home plate by a player during a baseball game. Which kind of basic movement skill is demonstrated by this action?", ["Manipulative", "Non-locomotor", "Locomotor", "Rhythmic"], 0),
    ("During a six-week training program, it is your responsibility as a Physical Education teacher to evaluate and track your students' progress in flexibility. Which fitness test from the list below would be best suited to monitor gains in lower back and hamstring flexibility?", ["Body Mass Index (BMI) test", "Shuttle run with cone obstacles", "1 Repetition Maximum (1RM) bench press", "Sit and Reach test"], 3),
    ("A male 15-year-old performs below average in cardiovascular endurance exercises (e.g., 1.5-mile run) but significantly above average in muscular strength pattern probably mean for his training habits as his PE teacher?", ["Lack of motivation in testing", "A need for more flexibility work", "Disproportionate training routine", "Advanced development of VO2 max"], 2),
    ("In a basketball class, a Physical Education teacher notices that a number of students are having trouble with proper shooting mechanics. The teacher should proceed after going over skill checklists and finding recurring problems with balance and follow-through. What should the teacher do?", ["Eliminate basketball from the curriculum", "Focus on scrimmages instead", "Create targeted shooting drills for improvement", "Assign research on famous shooters and defensive players"], 2),
    ("A 40-year-old office worker's hips and shoulders become stiff from extended sitting. Which of the following exercises would be best suited to suggest to help restore joint mobility and general flexibility?", ["Low-distance cycling", "Jump squats", "Punching bag workouts", "Static stretching"], 3),
    ("Balance boards are introduced by a strength and conditioning coach to athletes recuperating from ankle sprains during preseason conditioning. As part of their daily routine, he gives them instructions to make dynamic movements on the boards. Which mechanism of injury prevention is this strategy specifically aiming to address?", ["Proprioceptive enhancement", "Flexibility development", "Visual acuity training", "Cardiorespiratory endurance"], 0),
    ("The weekly lesson that a second-grade Physical Education teacher plans is in line with the students' social, cognitive, and physical development. What would be the most advantageous and developmentally appropriate activity to incorporate into the lesson plan?", ["Weightlifting sessions to build muscle strength", "Teaching tactical strategies for competitive team sports", "Incorporating relay games that involve running, coordination, and teamwork", "Practicing complex dance routines with advanced choreography"], 2),
    ("A fitness coach notices that a participant's breathing has accelerated, his heart rate has risen sharply, and he seems extremely alert and energized during a high-intensity interval training (HIIT) session. According to the coach, this reaction results from the body's quick hormonal adjustment to meet the energy requirements of vigorous exercise. Which hormonal shift is most likely responsible for this physiological response?", ["Decrease in cortisol", "Increase in insulin", "Rise in adrenaline", "Drop in growth hormone"], 2),

    # --- Section 2 (Q51 to Q100) ---
    ("A varsity basketball player routinely makes accurate shots during free-throw drills without glancing down at their hands or giving the movement any conscious thought. Which stage of motor learning is best exemplified by this situation?", ["Conscious effort in movements", "Effortless execution", "Frequent errors", "Beginners needing demonstration"], 1),
    ("How do manipulative skills benefit team games?", ["They help improve overall breathing capacity efficiency.", "They improve joint flexibility", "They reduce the heart rate", "They ensure object control and passing"], 3),
    ("What is the MAIN GOAL of the PHYSICAL EDUCATION PROGRAM'S IMPLEMENTATION?", ["To write annual teaching reports", "To organize sports tournaments", "To execute planned activities that promote physical and health literacy", "To evaluate past teachers' instructional strategies and their competencies"], 2),
    ("The second runner in a competitive relay race watches the approaching teammate closely. They coordinate their speed in the exchange zone and extend their hand at the right moment to grab the baton without breaking stride. What is being employed?", ["Movement across different body positions", "Reaction time and coordination", "Flexibility", "Body composition"], 1),
    ("Which ancient society is most commonly recognized for having incorporated physical training into formal education to prepare students for war?", ["Ancient India", "Ancient Egypt", "Ancient Greece", "Ancient China"], 2),
    ("As a Physical Education teacher, it is your responsibility to assist a group of sedentary students in forming fitness habits that will last a lifetime. Which of the following fitness techniques would best encourage long-term adherence and integration into their daily lives, taking into account their hectic academic schedules, restricted access to gym facilities, and differing motivation levels?", ["Weekend-only workouts", "60-minute gym sessions daily", "15-minute or 30 min walk after each meal", "Annual sportsfest participation"], 2),
    ("An activity that fosters leadership, teamwork, and the development of sport-specific skills is being created for senior high school students by a Physical Education teacher. Out of all the activities listed, which one would be best to incorporate into the curriculum?", ["Peer-led volleyball drills", "Jump rope rhymes", "Counting colors", "Clay modeling"], 0),
    ("During a high-intensity tag game, a student sees an opponent coming up from behind. They quickly turn, speed up, and move between two other players to avoid being tagged. What skill is mainly being shown?", ["Stability", "Agility", "Flexibility", "Body composition"], 1),
    ("Why is reaction time critical in badminton?", ["For building endurance", "For hitting the shuttle quickly", "For dancing performance", "Tool used for measuring heart rate"], 1),
    ("When learning a new gymnastics routine, a student frequently makes mistakes and considers every move. Which motor learning stage best characterizes this behavior?", ["Reflexive", "Autonomous", "Associative", "Cognitive"], 3),
    ("What term describes an increase in body size and structure?", ["Maturation", "Development", "Coordination", "Biological growth"], 3),
    ("What is the main purpose of peer assessment in PE?", ["To provide constructive feedback", "To criticize the technique", "To negatively judge the technique.", "To reduce workload"], 0),
    ("In a diverse neighborhood with little access to gyms or other official exercise facilities, you have been entrusted with encouraging fitness practices that improve health. Which innovative approach is most likely to inspire broad participation and encourage sustained physical activity when taking reach, engagement, and sustainability into account?", ["Conduct a one-time lecture", "Post fitness challenges on local social media groups", "Assign PE homework to students", "Create a research study on fitness standards and sports"], 1),
    ("Coach Santiago gives each player instructions to reach their toes and hold the position during the warm-up before a volleyball match in order to get their muscles ready for play. In this situation, which non-locomotor skill requires muscle elongation?", ["Jumping", "Stretching", "Leaping", "Catching"], 1),
    ("When learning how to shoot a basketball, two students of the same age demonstrate varying levels of progress. Which of the following best describes the difference?", ["Individual learning styles and motivation", "Gender identity", "Type of feedback used", "Order of practice activities"], 0),
    ("Why are locomotor skills important in Physical Education?", ["They improve and develop their body's flexibility.", "They are only used in dance", "They improve object manipulation", "They allow movement across space"], 3),
    ("Coach Mira has noticed that a number of the kids on her beginner soccer team have trouble changing direction quickly and frequently trip or fall during frantic drills. She wants to incorporate a dynamic play activity that will improve their coordination and reduce the possibility of non-contact injuries. In order to enhance the kids' coordination and lower their risk of injury, what exercise should Coach Mira incorporate into the training session?", ["Practicing agility ladder drills", "Standing still while balancing", "Lifting weights without movement", "Passive stretching for long durations"], 0),
    ("What aspect of motor skills gauges motion?", ["Balance", "Reaction time", "Accuracy", "Speed"], 3),
    ("Which element best explains a discrepancy between expected learning outcomes and actual student performance when examining the implementation of the PE curriculum?", ["Students' disinterest in physical activities", "Inadequate equipment and poor assessment methods.", "The lack of available referees and game officials", "The popularity of online games over physical activity"], 1),
    ("When opponents are getting ready to throw in a heated dodgeball match, a player will frequently move laterally, or side to side. In what ways does this movement improve the player's performance the most?", ["Confusion", "Defensive strategy", "Tactical awareness", "Predictability"], 2),
    ("Based on age appropriateness, safety, and motor skill readiness, which Physical Education lesson plan best suits the developmental stage of fourth-graders?", ["Strength circuits using bodyweight", "Yoga headstands", "Powerlifting drills", "Marathon running builds mental strength"], 0),
    ("Why are movement screening tools used?", ["To improve academic performance", "To detect weaknesses and prevent injury", "To build endurance", "To evaluate intelligence"], 1),
    ("What does the FITT principle's \"F\" stand for?", ["Flexibility", "Function", "Frequency", "Focus"], 2),
    ("Which of the following is a skill that involves manipulation?", ["Catching", "Skipping", "Balancing", "Twisting"], 0),
    ("As a Physical Education instructor, you have been assigned to assist a group of novices in becoming more fit overall. Creating a one-week training schedule that encourages muscular strength and cardiovascular endurance while taking rest and recuperation into account to avoid injury is your aim. Which of the following workout regimens is best suited for this novice group?", ["5 days of strength training", "Alternate cardio and strength training with 2 rest days", "Cardio only for T days straight in one or two months", "High-intensity daily circuits without rest"], 1),
    ("Maria, the team's outside hitter, jumped for a spike during a crucial varsity volleyball match and landed awkwardly. Although no other player touched her, she instantly passed out and clutched her knee. Which factor should be given priority in the athletic trainer's immediate injury assessment to help identify the injury's underlying cause?", ["Sleep and diet logs", "Number of games played", "Shoe brand and color", "Jump mechanics and landing technique"], 3),
    ("Which definition of \"program planning\" in Physical Education and health is the most accurate?", ["Designing learning goals and strategies based on student needs", "Delivering activities that meet national and International sports goals", "Observing students during physical exercises", "Recording grades and performance in a class roster"], 0),
    ("A coach suggests using the FITT principle to safely increase workout intensity during a strength training session. To accomplish that, which of the following actions appropriately applies the principle?", ["Reducing the number of sets in each exercise", "Increasing the amount of weight used in resistance training", "Limiting water intake during the workout session", "Wearing tighter athletic clothing to reduce air resistance"], 1),
    ("Which of the following describes a skill-related aspect of fitness?", ["Muscular strength", "Flexibility", "Agility", "Cardiovascular endurance"], 2),
    ("Coach Luis observes that one of his players, Mark, abruptly passes out while running for the ball during a weekend inter-school soccer competition. At the moment, no other player was close to him. Mark seems to be in pain as he holds his ankle. As the coach, what should Coach Luis do first in this scenario?", ["Fracture: apply direct pressure", "Sprain; apply R.I.C.E. method", "Concussion; check for responsiveness", "Contusion; massage the area"], 1),
    ("A Physical Education instructor is creating a year-round curriculum for a multicultural class that comprises pupils with different learning styles, cultural backgrounds, and physical capabilities. Ensuring that every student feels successful, motivated, and included during physical activities is the aim. Which strategy would most effectively show the instructor's capacity to design an inclusive Physical Education curriculum?", ["Use the same warm-up routine for all students.", "Differentiate activities by ability.", "Grade students only on performance speed.", "Separate students by ability into different groups permanently."], 1),
    ("The purpose of a study is to investigate the individual experiences and opinions of Physical Education students regarding a novel program. Which approach would enable the researcher to examine detailed accounts and uncover hidden meanings in the responses from the students?", ["Survey", "Fitness test", "Interview", "ANOVA"], 2),
    ("An athlete's Functional Movement Screen (FMS) result indicates weak trunk stability, affecting their balance and posture during performance. As their coach, which of the following exercises would you integrate into their training plan to directly address this deficiency?", ["Plank holds", "Sit and reach", "Jumping drills", "Arm circles"], 0),
    ("For a client who wishes to increase cardiovascular endurance, you would be creating a weekly exercise program. Which of the following exercises would be best to incorporate into their program regularly in light of this goal?", ["20-minute jogging", "Bench press", "Sprinting 30 meters", "High jump"], 0),
    ("Why is it important to know age-specific fitness standards?", ["To ensure equal competition", "To tailor health plans", "To avoid injury only", "To reduce physical activity"], 1),
    ("Mr. Santos, a 45-year-old office worker who has been sedentary for the past ten years, needs a customized exercise program created by a fitness trainer. The trainer observes during the evaluation that Mr. Santos finds it difficult to perform exercises that call for a broad range of motion, like deep squats and overhead stretches. Which physiological adaptation should the trainer focus on to safely meet his needs in the beginner program?", ["Higher heart rate max", "Faster muscle recovery", "Reduced joint flexibility", "Stronger bone density"], 2),
    ("To prepare their bodies for intense physical activity, the coach asks athletes to perform various basic movement patterns during a warm-up before a school sports competition. Which of the athletes' motions below best exemplifies a locomotor skill?", ["Twisting", "Stretching", "Balancing", "Leaping"], 3),
    ("As a Physical Education instructor, you are getting your students ready for a rigorous fitness test that involves agility and sprinting. Creating a warm-up regimen that maximizes the activation of major muscle groups, improves neuromuscular readiness, and reduces the risk of injury is your aim. Which of the following warm-up exercises best demonstrates your expertise and inventiveness in creating a successful pre-activity routine?", ["Light jog → arm swings → dynamic stretches → short sprints", "Static stretch → rest → jog → water break → sit and reach → light jog", "Jumping jacks only", "Sit and reach for 10 minutes"], 0),
    ("Jeric cycles five days a week for eight weeks in a row after enrolling in a fitness program. He observes that he is less tired after riding longer distances. What most likely accounts for his enhanced endurance performance based on physiological changes brought on by aerobic training?", ["Decreased stroke volume", "Reduced cardiac output", "Loss of muscle mass", "Enhanced capillary density"], 3),
    ("Creating a unit for Grade 9 students that combines physical fitness exercises with hygiene education is the responsibility of a Physical Education teacher. Four tactics are suggested during a faculty consultation to promote student responsibility and involvement. Which of the following approaches, in your opinion as an assessor, would best help adolescents develop both conceptual understanding and personal accountability?", ["Student-designed hygiene fitness log", "Provide handouts on hygiene rules", "Show videos about gym etiquette", "Ask students to memorize hygiene facts"], 0),
    ("The curriculum is being reviewed by a Physical Education teacher to make sure middle childhood students (ages 6-12) are gradually acquiring the necessary physical skills. The teacher observes that pupils in higher grade levels are having difficulty with increasingly intricate movement patterns. How can the instructor most effectively assess and enhance the program's skill-building progression?", ["Use identical drills for all grade levels", "Teaching complex basketball plays enhances team coordination.", "Break down activities into increasingly complex components", "Ask students to list their favorite activities"], 2),
    ("Which of the following best supports Physical Education's main goal of fostering emotional growth?", ["Enhancing cardiovascular endurance", "Movement relieves anxiety", "Developing flexibility and balance", "Improving fine motor skills"], 1),
    ("When the score is tied in the last seconds of a basketball game, a student-athlete is given two free throws. What mental technique should the player employ to keep their cool and perform better in the face of crowd noise and pressure?", ["Focus and mental rehearsal", "Biomechanical calculation", "Tactical retreat", "External coaching"], 0),
    ("Several students sustain minor injuries during a Physical Education class that focuses on dynamic sports like basketball and soccer. What is the best course of action for the PE teacher to reduce these kinds of incidents in subsequent classes?", ["Begin with skipping and light stretching", "Teach correct movement patterns and techniques", "Limit students' water breaks", "Eliminate skill-building drills altogether"], 1),
    ("Which element describes the capacity for fast direction changes?", ["Balance", "Agility", "Power", "Speed"], 1),
    ("Coach Ben instructed the volleyball players to stand still and do stretching, twisting, and balancing exercises as part of their warm-up. What kind of movement entails remaining motionless while moving body parts?", ["Locomotor", "Manipulative", "Non-locomotor", "Rhythmic"], 2),
    ("Student-athlete Marco is engaged in his routine interval training, which consists of quick bursts of intense running interspersed with rest intervals. His breathing has become more rhythmic, and his muscle fatigue has subsided after 20 minutes of the workout, which enables him to continue performing without slowing down. At this point in the workout, which physiological change most likely helps Marco maintain his effort?", ["Oxygen delivery to muscles improves", "Stored fat usage increases rapidly", "Lactic acid fully neutralizes", "Metabolic rate drops sharply"], 0),
    ("Which tool allows breaking down performance visually for feedback?", ["Observation chart", "Video analysis", "Reaction timer", "Peer evaluation"], 1),
    ("During PE class, a student tries a high jump but lands awkwardly and feels slight discomfort in the knee. After the teacher advises them to bend their knees more and extend their arms for better balance, the student improves their technique on the next attempt. What skill is being developed?", ["Understanding flight", "Effective strategies for memorizing information efficiently", "Applying biomechanical feedback", "Counting repetitions"], 2),
    ("You are creating a task to evaluate pupils' comprehension of basic movement concepts. Which exercise best enables students to show that they can use ideas like balance, coordination, and biomechanics in a real-world setting?", ["Watch an educational health and fitness video presentation.", "Answer a short test.", "Study from the textbook.", "Design their warm-up routine"], 3),

    # --- Section 3 (Q101 to Q150) ---
    ("What is the focus of cardiovascular endurance?", ["Flexibility", "Heart and lung efficiency", "Muscle strength", "Reaction time"], 1),
    ("After running sessions, several beginning student-athletes frequently complain of lower leg pain, according to a Physical Education teacher. She notes that their training incorporates abrupt, high-intensity running drills and lacks formal warm-ups. What is the best course of action for the teacher to take to lessen the likelihood of shin splints happening again?", ["Switch to high-carb diets", "Increase the frequency of hill sprints", "Introduce proper warm-up and stretching", "Eliminate all running from training"], 2),
    ("When participating in team games, several students with lower motor skill proficiency tend to withdraw or hesitate. What is the teacher's best course of action to guarantee that every student is involved and feels included?", ["Modify the rules and roles to allow varied participation", "Exclude team games from the program", "Pair low-skilled students together to avoid frustration", "Continue with standard gameplay for all students"], 0),
    ("Students should be able to demonstrate their comprehension and application of fitness concepts through a thorough final project in Health and Physical Education. Which of the following best fulfills this objective?", ["Book report", "Personal fitness plan creation", "Written exam only", "Reflective personal reading record"], 1),
    ("For the past four weeks, James has been lifting weights regularly. His coach suggested increasing the weight in his routine every two weeks to make sure he keeps gaining muscle strength. This tactic aims to keep his performance from stagnating and assist his body in adjusting to the growing challenge. Which training principle is being used in this situation, where the resistance is being increased gradually?", ["Specificity", "Progression", "Recovery", "Variation"], 1),
    ("During a competitive basketball game, a player uses a quick crossover dribble and then suddenly changes direction. This helps the player get past a defender and make space for a jump shot. What motor skill is being used in this situation?", ["Dribbling skill", "Shooting Skill", "Manipulative skill", "Defensive skill"], 2),
    ("A PE teacher observed a pattern in one student's results during the Grade 11 students' quarterly fitness evaluation: the student's Body Mass Index (BMI) considerably improved, and the student showed increased flexibility during the sit-and-reach test. In contrast to the prior quarter, the student's push-up test score decreased. The student reports doing yoga, going for a brisk walk, and doing some light stretching every day. What is the best course of action for the teacher to address the loss of muscle strength in the light of the assessment results and the students' physical activity patterns?", ["Increase stretching routines and goal setting", "Add bodyweight or resistance training", "Reduce cardio sessions", "Stop cool-down exercises"], 1),
    ("Which phase of motor learning entails practicing the skill to make it better?", ["Cognitive", "Associative", "Automatic", "Preparatory"], 1),
    ("Which corrective focus should you prioritize as a Physical Education teacher to avert possible injuries?", ["Increase hamstring flexibility through dynamic stretching routines", "Provide nutritional counseling to reduce body fat percentage", "Incorporate agility drills to enhance reaction time", "Implement strength and technique training to correct knee alignment"], 3),
    ("Coach Rivera has noticed that during fast breaks, her team finds it difficult to keep possession of the ball. She creates practice sessions that focus on dribbling through cones, changing directions, and keeping ball control under pressure in focusing on in this training?", ["Locomotor", "Non-locomotor", "Aerobic", "Manipulative"], 3),
    ("Students are given heart rate monitors to use during circuit training by a Physical Education teacher. A student asks why the device is required, stating that they can already tell how exhausted they are. Which of the following, in your opinion as a student assessing the application of heart rate monitors in physical activity, best supports their use in this context?", ["They count calories burned accurately.", "They eliminate the need for warm-ups.", "They ensure exercise stays within target zones.", "They improve posture automatically base in the fitness manual"], 2),
    ("During a training session, a basketball coach asks players to perform 60-second hamstring static stretches immediately before explosive sprint drills. After several repetitions, the athletes notice reduced sprint speed and weaker jumping performance. Which explanation BEST accounts for this outcome?", ["Static stretching increases muscle spindle activity, causing stronger muscle contractions.", "Prolonged static stretching before power activities may temporarily reduce muscle force production and neuromuscular efficiency.", "Static stretching rapidly increases lactic acid production, leading to muscle fatigue.", "Static stretching primarily strengthens fast-twitch muscle fibers, making movement less coordinated."], 1),
    ("Mark observes that his breathing deepens and speeds up to meet his muscles’ oxygen demands during a high-intensity aerobic workout. What bodily system is principally in charge of this alteration in breathing patterns?", ["Circulatory", "Respiratory", "Digestive", "Lymphatic"], 1),
    ("A Physical Education teacher watches a student run 400 meters during a high school intramural. The instructor then asks the class to determine which immediate physiological change in the student's body was most likely caused by the short, intense effort. During the sprint, which of the following reactions is most likely to happen?", ["Decreased heart rate", "Elevated blood oxygen saturation", "Reduced respiration rate", "Increased muscle temperature"], 3),
    ("During a school dance recital, a student skillfully combines twisting, reaching, and bending movements. They stay coordinated with the music and express emotion throughout the routine. What type of motor skill is the student using?", ["Non-locomotor skill application", "Cardio exercise application", "Strength training application", "Locomotor skill application"], 0),
    ("A basketball player takes a fast break by running down the court during a game, Which word best characterizes this kind of movement of the body from one location to another?", ["Locomotor skill", "Static movement", "Stability control", "Kinesthetic motion"], 0),
    ("Mr. Santos watches his fifth-graders as they move in various patterns throughout the gym during a Physical Education lesson. He tells them to hop back to the starting line after skipping to the far wall. Following the exercise, he records each student's form, rhythm, and spatial mobility. In this exercise, what kind of motor skills is Mr. Santos mainly evaluating?", ["Non-locomotor skills", "Locomotor skills", "Manipulative skills", "Cognitive skills"], 1),
    ("Coach Ana notices that the players frequently bump into one another or miss returns because of bad positioning during a table tennis doubles match. She reminds them to cover their side of the table and pay attention to where they are and where their partner is. What concept is emphasized?", ["Hand-eye coordination", "Reaction time", "Space awareness", "Speed and agility"], 2),
    ("Which of the following describes a fitness component that has to do with health?", ["Agility", "Coordination", "Reaction time", "Cardiovascular endurance"], 3),
    ("How does video analysis help improve skills?", ["It creates fitness plans", "Records and tracks daily attendance data.", "It provides visual feedback", "It reduces exercise time"], 2),
    ("Why is tracking fitness progress important?", ["To criticize students", "To motivate ongoing improvement", "Compete fairly and strongly with others.", "To skip fitness tests"], 1),
    ("In order to better encourage students to DEVELOP LIFELONG FITNESS HABITS, a school principal is updating the PHYSICAL EDUCATION CURRICULUM. At a faculty meeting, four proposals were made: Proposal A: To improve athletic performance, all students should be required to try out for competitive varsity teams. Proposal B: Establish a year-round Physical Education program that accommodates a variety of interests and skill levels by providing a broad range of physical activities like dance, swimming, recreational games, and fitness Proposal C: To free up more time for academic subjects, schedule Physical Education just once a week. Proposal D: Conduct written health and fitness tests every three months in place of physical activity sessions. Which suggestion best advances the objective of encouraging physical activity throughout one's life?", ["Mandating students join varsity teams", "Providing diverse physical activities year-round", "Limiting Physical Education to once or twice a week", "Replacing PE with written health tests"], 1),
    ("Which system controls the body's voluntary movements?", ["Digestive", "Nervous", "Circulatory", "Respiratory"], 1),
    ("Two students evaluate their fitness levels in class, one using the Fitness Gram test and the other using the Philippine Physical Fitness Standards. They observe that their scores vary despite doing the same number of sit-ups. The instructor explains that in order to guarantee fair assessment, each system evaluates results using particular criteria. Which principle, given the circumstances, is used in both fitness testing systems to explain this discrepancy?", ["Uniform scoring for all ages", "Age- and sex-specific benchmarks", "Randomized test sequence", "Only cardiovascular components tested"], 1),
    ("Which ancient society is renowned for its use of Physical Education in military instruction?", ["Rome", "Greece", "Egypt", "India"], 0),
    ("A volleyball player initiates a rally by throwing the ball and hitting it over the net. Which basic motor skill is being displayed?", ["Serving", "Running", "Skipping", "Balancing"], 0),
    ("Which two systems collaborate closely to deliver oxygen and eliminate carbon dioxide from working muscles during high-intensity exercise?", ["Nervous and skeletal", "Digestive and endocrine", "Muscular and integumentary", "Cardiovascular and respiratory"], 3),
    ("Tasks requiring fine motor skills, like cutting paper and holding a pencil correctly, are consistently difficult for a student in Grade 2. Which of the following interventions would be best to use in the classroom as a Physical Education teacher to directly enhance the fine motor development of the students?", ["Include short jogging sessions during recess to improve overall stamina", "Provide daily guided writing and drawing exercises during class activities", "Introduce jumping jacks and skipping routines for cardiovascular health", "Add sprint drills to enhance lower body strength and speed"], 1),
    ("In the associative stage of motor development, which would be most advantageous to a student?", ["Blocked practice with no variation", "Varied drills, occasional feedback", "Constant feedback after each trial", "Watching videos of elite performers"], 1),
    ("A student's muscular endurance significantly improved during the midterm fitness test, but its flexibility did not. Which training combination most likely resulted in this imbalance, based on the student's training log?", ["Excessive resistance training, minimal stretching", "High cardiovascular sessions, light strength work", "Warm-up only with light jogging", "Balanced use of all fitness components"], 0),
    ("Several students in a Grade 11 Physical Education class demonstrated moderate muscular strength and low cardiovascular endurance after a fitness assessment. The instructor assigns students to use the SMART goal-setting technique to develop an improvement plan. What is the direct connection between this method and efficient post-fitness test planning?", ["It offers personalized benchmarks based on test interpretation.", "It improves flexibility outcomes.", "It removes the need for criterion-referenced standards.", "It encourages equal improvement across all components and standards activities."], 0),
    ("A coach creates an exercise for a kids' sports clinic that focuses on honing basic movement skills like jumping, skipping, and hopping. Participants who are just starting to learn these fundamental locomotor skills are the target audience for the clinic. Which age range does the coach most likely work with?", ["Infants", "Toddlers", "Preschoolers", "Adolescents"], 2),
    ("To assist students in maintaining regular physical activity in spite of everyday obstacles like bad weather, time constraints, or a lack of supervision, a Physical Education teacher gave them a fitness log project. Following a week, the following student answers were noted: Which student best exemplifies how to get past typical obstacles to consistent exercise?", ["Juan quits jogging due to rain.", "Anna adjusts her schedule to fit 15-minute HIIT indoors.", "Lea delays workouts until next year to extend the preparation of his HIIT", "Carlo skips training when his coach is absent."], 1),
    ("How do criterion-referenced standards help in fitness testing?", ["They compare students to others", "They give numerical IQ values", "They determine if goals are met", "They focus on skill learning"], 2),
    ("A student has exceptional agility, but when engaging in prolonged physical activity, they show poor endurance. In terms of the components of overall physical fitness, which of the following best describes this condition?", ["Overtraining", "Balanced strength and power", "Healthy flexibility", "Imbalanced fitness profile"], 3),
    ("A student's cardiovascular endurance, muscular strength, muscular endurance, and body composition all show discernible improvements throughout a semester-long fitness program. Flexibility is still below the anticipated level, though. What should a Physical Education teacher do when assessing a student's training plan?", ["Declare the plan a failure", "Recommend stretching twice or thrice a month every year", "Modify the plan to incorporate dynamic and static stretching", "Ignore the issue as flexibility is not essential"], 2),
    ("What is measured by the Sit and Reach Test?", ["Cardiovascular endurance", "Body composition", "Muscular strength", "Flexibility"], 3),
    ("Body composition primarily refers to______?", ["bone density", "muscle bulk", "fat and lean mass ratio", "lung capacity"], 2),
    ("What is the relationship between the muscular and skeletal systems?", ["They support and move the body.", "They remove toxins.", "They digest nutrients.", "They produce hormones."], 0),
    ("How do non-locomotor skills differ from locomotor skills?", ["They use more energy", "They are much simpler to conduct.", "They involve staying in place", "They require equipment"], 2),
    ("What does balance help a gymnast maintain during a routine?", ["Stability and body control", "Manipulating objects with precision and coordinated body movement.", "Ability to move joints through full range.", "Strength"], 0),
    ("Which element emphasizes the use of data to update or enhance Physical Education programs?", ["Implementation", "Documentation", "Goal Setting", "Evaluation"], 3),
    ("A researcher intends to evaluate how resistance bands affect muscle endurance and strength. Which step must the researcher take to make sure the investigation adheres to the scientific method before starting the actual study?", ["Formulate a hypothesis", "Begin training", "Publish immediately", "Skip pilot tests"], 0),
    ("What is the main purpose of manipulative skills in sports?", ["To control objects like ball", "Enhance stability through focused balance training exercises.", "To build endurance", "To prevent injuries"], 0),
    ("Which fitness component refers to the range of motion around joints?", ["Strength", "Agility", "Flexibility", "Endurance"], 2),
    ("Why is warming up before an activity important?", ["To build endurance", "To burn more calories", "To shorten exercise time", "To prevent injury"], 3),
    ("What is the main movement pattern used in sprinting?", ["Non-locomotor", "Manipulative", "Rhythmic", "Locomotor"], 3),
    ("As a new Physical Education instructor, you are tasked with overseeing a preschool class of four to five-year-olds. Choosing a set of exercises for your weekly Physical Education class is your responsibility. You are advised to concentrate on developmentally appropriate methods that improve young learners enjoyment, safety, and motor skill development. Which set of exercises, given the circumstances, would make up the most developmentally appropriate early childhood Physical Education program?", ["Basketball scrimmage, sit-ups, long jump", "Relay races, tag games, balancing activities", "Weightlifting, soccer matches, obstacle courses", "Daily jogging, aerobics routines, yoga"], 1),
    ("What does inclusivity mainly guarantee when it comes to the creation of Physical Education programs?", ["That all equipment is used properly", "That activities are appropriate and accessible for all learners", "That students compete at equal skill levels", "That students learn only team-based sports and Individual sports"], 1),
    ("You prepare a weekly Physical Education lesson as a school teacher. Which of the following lesson objectives is appropriate for preschool Physical Education? Your students are between the ages of 4 and 5 and are developing their muscle control, balance, and coordination.", ["Define anaerobic threshold", "Master sprinting, jumps, and throws", "Develop hopping and skipping skills", "Analyze biomechanics"], 2)
]

os.makedirs('lib/data/bped_ppst_drill_8', exist_ok=True)

def generate_section(sec_id, start_idx, end_idx):
    sec_items = raw_items[start_idx:end_idx]
    code = f"import '../../models/question.dart';\n\n"
    code += f"const List<Question> bpedPpstDrill8Section{sec_id}Questions = [\n"
    
    for local_idx, (q_text, opts, corr_idx) in enumerate(sec_items):
        q_id = start_idx + local_idx + 1
        opts_formatted = ",\n      ".join([repr(o) for o in opts])
        code += f"  Question(\n"
        code += f"    id: {q_id},\n"
        code += f"    questionText:\n        {repr(q_text)},\n"
        code += f"    options: [\n      {opts_formatted},\n    ],\n"
        code += f"    correctAnswerIndex: {corr_idx},\n"
        code += f"  ),\n"
        
    code += "];\n"
    
    file_path = f"lib/data/bped_ppst_drill_8/bped_ppst_drill_8_section_{sec_id}.dart"
    with open(file_path, "w") as f:
        f.write(code)
    print(f"Generated {file_path} with {len(sec_items)} items.")

generate_section(1, 0, 50)
generate_section(2, 50, 100)
generate_section(3, 100, 150)

print("All 3 BPED PPST Drill 8 section files successfully generated!")
