import os
import json

raw_items = [
    # --- Section 1 (Q1 to Q50) ---
    ("A student sets up several targets at different heights and distances during Physical Education class. To hit each target successfully, they constantly modify their stance, force, and angle. Which idea is being used in this exercise?", ["Skill variation and accuracy", "Strength training", "Skill memorization", "Enhancing overall body flexibility"], 0),
    ("Players must regularly receive and pass the ball under pressure during a soccer match. What role do manipulative abilities play in a player's performance in these kinds of gaming scenarios?", ["By improving singing rhythm", "By helping players balance better", "By improving ball control and passing accuracy", "By increasing speed alone"], 2),
    ("During basketball practice, Coach Rivera observes that his players can now make lay-ups more fluidly and with fewer errors than when they first began. Which motor learning stage do the athletes most likely belong to?", ["Associative", "Cognitive", "Reflexive", "Autonomous"], 0),
    ("A soccer player uses a header to guide the ball toward the goal after receiving a cross from a teammate. Later, for a volley shot, the same player hits the ball in mid-air. Which set of skills is being used in these actions?", ["Manipulative skills in gameplay", "Imaginative and engaging play experience", "Non-locomotor", "Cardiovascular training"], 0),
    ("An athlete keeps a composed stance as he switches between moves during a gymnastics routine on the balance beam. How does gymnastics benefit from balance?", ["It helps the gymnast jump higher.", "It prevents injuries from running.", "It allows steady control on apparatus.", "It speeds up movements."], 2),
    ("A PE teacher discovers that students have trouble with flexibility exercises after finishing a fitness module. To incorporate more dynamic stretching exercises into her next lesson, she goes over her journal entries. Which ability is she using?", ["Diagnostic testing", "Peer evaluation", "Reflective practice", "Differentiation"], 2),
    ("The coach observes that the opposing team is continuously attacking through the right wing during an interclass football tournament. In order to improve defensive coverage on that side and strengthen midfield control, the coach tells the team to switch to a 4-5-1 formation at halftime. This choice best illustrates:", ["Spontaneity of movement", "Carelessness", "Predictability", "Tactic-based improvisation"], 3),
    ("A student reviews his fitness test results, which show high flexibility but low cardiovascular endurance, and compares them to the suggested fitness standards. What inferences can he make regarding the importance of his physical health?", ["He is equally skilled in all areas.", "His fitness is unbalanced.", "He needs no improvement.", "He is overtrained."], 1),
    ("Mr. Santos asked each student to establish a personal fitness goal for the semester during the first week of Physical Education class. Which goal-setting strategy is most effective in enhancing performance in Physical Education activities, given that Maria chose to \"just try to be better at sports\" and Joshua set a goal to \"increase his shuttle run time by 2 seconds in 8 weeks\"?", ["Generic and long-term", "Vague and flexible", "Influenced by peer pressure", "Personalized and measurable"], 3),
    ("A Physical Education teacher notices that a student has trouble with body coordination during landings and transitions during an evaluation of a gymnastics routine. The teacher wants to use a tool that lets both the student and the teacher examine performance in detail and pinpoint specific mistakes in form and technique in order to help the student get better. Which is the best tool to use for this?", ["Stopwatch", "Video playback", "Caliper", "BMI scale"], 1),
    ("Before a school intramural basketball game, a student leads his teammates through a self-designed warm-up routine that includes light jogging and dynamic stretches. What concept is the student applying in this situation?", ["Passive watching", "Pre-performance preparation", "Game-based point accumulation system", "Peer assessment"], 1),
    ("A student submits a video of their dance routine while following the teacher's instructions as part of a performance task in Physical Education class to show that they have mastered timing and coordination. What kind of assessment tool is the teacher using to evaluate the student's performance on the video by way of a checklist with specific criteria?", ["Digital performance task", "Portfolio", "Rubric", "Self-check"], 2),
    ("A student starts a stretching regimen three times a week, concentrating on hamstring and lower back stretches, after failing to reach past his toes on a flexibility test in Physical Education class. His range of motion gradually gets better. Which fitness principle is being used by the student?", ["Flexibility improvement techniques", "Comprehensive physical fitness assessment", "Dance training", "Muscular strength planning"], 0),
    ("When a Physical Education teacher looks over the students' fitness logs, she notices that the majority of them routinely fall short of their daily step count targets. In accordance with developmentally appropriate practices, which of the following should the teacher do to successfully address this problem and encourage ongoing physical activity:", ["Punish students for lack of effort", "Cancel the activity", "Incorporate movement breaks", "Remove step count goal entirely"], 2),
    ("A Physical Education student decides that he needs to increase his cardiovascular endurance and aims to run two kilometers in less than twelve minutes. The student uses goal-setting and self-management skills to improve performance by adhering to a structured training program that incorporates interval runs and regular progress tracking. Which skill is being used?", ["Strength analysis", "Random performance", "SMART goal planning", "Food selection"], 2),
    ("A basketball player sees an open lane to the basket during a fast break and cuts through it before the defender can react. In this case, how can space awareness be useful?", ["It helps players position themselves strategically on the court.", "It aids athletes in effectively memorizing and recalling different strategic game plays.", "It keeps players from touching the ball too much.", "It improves cardiovascular endurance."], 0),
    ("During a PE class, a student changes their lower-body workout to lessen strain on a sore ankle while remaining active. What fitness principle is the student using?", ["Ignoring pain", "Overloading and Individualization", "Safety and modification", "Muscle testing"], 2),
    ("A defensive specialist closely watches the opposing setter's body positioning, eye direction, and hand movement just before the ball is released during a high-intensity volleyball match. What is this strategy's main goal?", ["Mind games", "Anticipating ball direction", "Delay tactics", "Time-wasting"], 1),
    ("During a gymnastics routine, an athlete does a handstand on a narrow balance beam and holds the position steadily for several seconds, even with some slight wobbling. What skill is mainly being shown in this moment?", ["Agility", "Static balance", "Power", "Coordination"], 1),
    ("Students move around the gym by skipping, hopping, and galloping in time with the music during a PE class game called \"freeze dance.\" The student instantly freezes in place when the music ends. What is demonstrated by this performance?", ["Reaction speed only", "Use of non-locomotor skills", "Developing long-lasting physical stamina", "Application of diverse locomotor patterns"], 3),
    ("A sprinter trains by repeatedly performing explosive leg drills like squat jumps and bounding to improve his ability to get off to a fast start at the start of a race. Which aspect of fitness are these drills primarily developing?", ["Flexibility", "Agility", "Power", "Endurance"], 2),
    ("Throughout track practice, a student gets feedback from peers about their sprinting technique. They change their arm movement and stride based on the advice. What skill or process is the student showing?", ["Formal testing", "Constructive criticism", "High-level competitive athletic performance", "Self-evaluation through peer input"], 3),
    ("In a singles tennis match, you see your opponent move remarkably slowly and hesitantly toward the net. What is the best tactical interpretation and reaction in the light of this situation?", ["Strong smash", "Defensive lob", "Weak return", "Service ace"], 2),
    ("A student creates a customized weekly fitness plan after learning about the various aspects of physical fitness. This plan includes a range of workouts, clear goals, and a progress chart to track advancements. What are they making?", ["A personal fitness program", "Strategic competitive action plan", "A report", "A class presentation"], 0),
    ("Coach Liza observes that while some players can already execute basic plays, others have trouble with lay-ups during a basketball practice for seventh-grade students. She modifies her exercises according to the students' skill levels and physical coordination. Why is it crucial that Coach Liza takes her students’ developmental stages into account when instructing them in sports skills?", ["To assign homework effectively", "To challenge advanced learners only", "To ensure tasks are suitable for students' physical readiness", "Maintain equal skill levels among all participants through consistent practice and instruction."], 2),
    ("Students work together in small groups to design an imaginative relay race that combines locomotor (running), non-locomotor (balancing), and manipulative (ball-passing or object-handling) skills. What kind of application of skills are the students exhibiting?", ["Creating a multi-skill activity", "Engaging in competitive group activity", "Reviewing sports drills", "Memorizing steps"], 0),
    ("A teacher is testing the students' ability to execute a proper inside-foot pass in football (soccer) during a Physical Education lesson. Students practice in pairs as she uses a performance checklist. Which of the following elements should suitably be on her checklist in order to guarantee an objective evaluation of the execution of motor skills?", ["Player personality", "Fan cheers", "Uniform neatness", "Foot placement, arm position"], 3),
    ("Using a performance rubric that includes criteria like form, release, and follow-through, your teacher gives you the task of evaluating a classmate's jump shot during basketball class. What should you do first to guarantee a fair and accurate evaluation?", ["Checklist survey", "Stopwatch", "Video analysis", "Scorecard"], 0),
    ("After a classmate recommends a high-intensity workout, the student assesses his current physical condition and training plan, then decides to decline the suggestion, explaining that it would interfere with his scheduled recovery. What type of thinking is being demonstrated?", ["Peer disagreement", "Value-based decision", "Detailed report on physical strength", "Fitness planning evaluation"], 3),
    ("To encourage students' physical activity and cultural awareness, a Physical Education teacher incorporates local folk dances like Tinikling and Pandanggo sa Ilaw into the program when organizing the school's intramurals. Which program planning principle is being used?", ["Cultural responsiveness", "Foreign influence", "Standardized practice", "Fitness over identity"], 0),
    ("A student designs a customized fitness program that incorporates jogging for cardiovascular endurance and push-ups for muscle strength. How does the idea of workout balance manifest itself in the combination of these exercises?", ["Identifying movement components", "Repetition tracking for exercise sets", "Performing drills", "Memorizing rules"], 0),
    ("Students do a group dance routine in Physical Education class. They are expected to assess one another's performances using a structured rubric that emphasizes timing, coordination, and energy. One student says, \"Watching others and getting comments on my moves helped me see what I needed to fix,\" after the activity. In this case, which major advantage of peer evaluation is best illustrated?", ["Increased competition", "Feedback and reflection", "Time-saving evaluation", "Eliminating teacher observation"], 1),
    ("The instructor presents a dance unit that incorporates Irish step dancing, Latin American salsa, and Philippine Tinikling during a Physical Education lesson. In addition to learning the moves, the students investigate each dance's cultural origins. Which best sums up the instructional approach being used?", ["A recreational break", "A warm-up variety", "Fitness conditioning", "Culturally responsive teaching"], 3),
    ("The opposing team constantly employs a high-block defensive technique at the net to thwart strong spikes during a volleyball match. What tactical choice should you make as the outside hitter to successfully counter this defensive setup and score a point?", ["Jump serve", "Soft drop shot", "Overhead block", "Float serve"], 1),
    ("The volleyball trainer assigns both static and dynamic stretching exercises to every player before a varsity volleyball match. Before the drills begin, one player asks why this is required. Why is stretching crucial for a warm-up in sports or Physical Education?", ["Increases anxiety and depression of the athletes", "Prepares muscles and improves flexibility", "Reduces muscle strength", "Prevents mental focus"], 1),
    ("A student chooses to incorporate rest days in between workouts to give his body time to recuperate after experiencing muscle soreness from rigorous training. Which fitness principle is being used by the student?", ["Power overload", "Coordination", "Muscle hypertrophy", "Safety and recovery"], 3),
    ("A student decides to up their weekly push-up and squat routine after experiencing fatigue during extended Physical Education activities. They can eventually perform more repetitions without rapidly becoming fatigued. Which fitness principle is being used here?", ["FITT (Frequency, Intensity, Time, Type)", "Static stretching", "Load balancing", "Passive recovery"], 0),
    ("Maria evaluates her performance after finishing a class fitness test and finds that she performed well in cardiovascular endurance but poorly in flexibility. After considering her stretching practices, she resolves to modify her weekly schedule in order to get better. Which action best exemplifies Maria's response?", ["Ignoring the results", "Compared to peers only", "Analyzing weaknesses and setting goals", "Complaining about scoring and results of referee"], 2),
    ("A coach observes that certain young children find it difficult to compete in basic relay races and ball games during a school sports day. According to the coach, these kids might not have fully formed their fundamental movement patterns yet. Why is it crucial for young children to acquire basic movement skills?", ["To increase academic grades", "Prevent injuries during recess through supervision, safe play, and proper equipment use.", "To build a strong foundation for future physical activities", "To learn new sports rules"], 2),
    ("In a tennis match, a player will quickly back-switch before launching himself forward in preparation for a strong serve. The stretch-shortening cycle in muscle movement is used in this action. In this case, which motor principle is being used?", ["Overload", "Stored elastic energy", "Progressive resistance", "Line of action"], 1),
    ("A Physical Education teacher uses a comprehensive rubric to assess students' javelin throws during a track and field test. Specific criteria like grip, approach run, release angle, and follow-through are included in the rubric. The teacher uses the rubric to score each performance as the students take turns. What is the main benefit of assessing physical performance with this type of tool?", ["Subjectivity", "Individualism", "Consistency", "Guesswork"], 2),
    ("In a Physical Education class, a student decides to hop rather than skip during a jump rope routine. Following the completion of both methods, the student explains that hopping improves rhythm control and saves more energy. Which skill is being assessed?", ["Speed only", "Skill preference", "Movement appropriateness", "Overall physical fitness and endurance"], 2),
    ("Four basketball skill stations are set up by the teacher during a Grade 8 Physical Education class: one focuses on the fundamentals of dribbling, another on passing drills, a fourth on lay-up technique, and the final one on mini scrimmage play. Based on an earlier assessment of their skill level, students are divided into stations that alternate every ten minutes. In this case, which teaching method is being used?", ["Rote repetition", "Differentiated instruction", "Homogenous grouping", "Random practice"], 1),
    ("The teacher observes that two students in a wheelchair are unable to fully engage in a typical basketball drill during Physical Education class. By lowering the hoop and permitting a bounce prior to a shot, the instructor alters the exercise. Which idea is the instructor using?", ["Competitive design", "Fitness grouping", "Adapted Physical Education", "Selective practice"], 2),
    ("Ms. Reyes is creating a weekly lesson plan during a Physical Education class. Due to short-term injuries, she observes that two of her students have restricted mobility. She adapts the stretching exercises to include seated and assisted stretches for those students to guarantee everyone can participate safely. Which idea does Ms. Reyes use when she plans her lessons?", ["Gender-based grouping", "Inclusion and UDL", "Standard assessment", "Competitive fitness"], 1),
    ("A student watches two classmates dribble during a basketball practice session and evaluates their technique, control, and consistency using a performance rubric. Which assessment technique is being used?", ["Personal opinion", "Performance-based rubric evaluation", "Reaction time testing", "Creatively developed scoring method"], 1),
    ("During a training session, a basketball coach asks players to perform 60-second hamstring static stretches immediately before explosive sprint drills. After several repetitions, the athletes notice reduced sprint speed and weaker jumping performance. Which explanation BEST accounts for this outcome?", ["Static stretching increases muscle spindle activity, causing stronger muscle contractions.", "Prolonged static stretching before power activities may temporarily reduce muscle force production and neuromuscular efficiency.", "Static stretching rapidly increases lactic acid production, leading to muscle fatigue.", "Static stretching primarily strengthens fast-twitch muscle fibers, making movement less coordinated."], 1),
    ("To track any changes in speed and endurance, a student regularly logs his 50-meter sprint times in a logbook throughout a two-week fitness program. The student observes a steady improvement after comparing the data. In this case, what principle is the student using?", ["Goal theory", "Reflection strategy for tracking", "Performance tracking", "Personality test"], 2),
    ("A teacher gives out little slips of paper after teaching a class on the human circulatory system, asking the students to write down one idea they fully understood and one unanswered question. To modify the lesson for the following day, the instructor reads it after class. What type of assessment is this?", ["Summative", "Diagnostic", "Formative", "Performance-based"], 2),
    ("Coach Lara observes that a number of basketball players find it difficult to stay motivated during practice. She chooses to use a customized training program to assist them in increasing their stamina. Which element ought to be her top priority in order to significantly increase their game endurance?", ["Powerlifting and training conditioning", "High-intensity interval training", "Static stretching", "Isolation drills"], 1),

    # --- Section 2 (Q51 to Q100) ---
    ("A Physical Education teacher finds, after looking over student feedback, that a lot of students feel left out when participating in team-based games and activities. How can a teacher use reflective practice to foster a more welcoming classroom environment?", ["Change all activities to individual performance-based tasks.", "Assign the students to choose their own teams.", "Design inclusive activities; monitor engagement weekly.", "Discuss the issue briefly, then resume usual routines."], 2),
    ("Plyometric jump drills, such as depth jumps and squat jumps, are incorporated into the weekly training regimen of varsity volleyball players by their coach. Players demonstrate higher blocks at the net and faster takeoffs during games. Which biomechanical principle best describes the enhanced explosive jumping ability based on this training application?", ["Greater mass", "Enhanced muscle elasticity", "Improved force absorption", "Lower heart rate"], 1),
    ("Using cooperative games, a Physical Education instructor creates a lesson where students must work together in mixed-ability groups to overcome a task. The main goals of this strategy are to:", ["Competition and ranking", "Speed and accuracy", "Inclusion and support", "Cognitive overload"], 2),
    ("A student sticks to a personal fitness plan three times a week. This includes strength training and cardio exercises. What principle of fitness are they using to keep or boost their health?", ["Studying anatomy and Biomechanic", "Applying consistent training", "Observing friends", "Memorizing routines"], 1),
    ("The coach watches as Team A continuously struggles to move the ball past midcourt during a modified 5-on-5 basketball game in Physical Education class. Due to the players' proximity to one another, passing is challenging, and turnovers are common. Which of the following is the best course of action when the coach stops the game to ask, \"What tactical adjustment can your team make to improve ball movement and reduce defensive pressure?\"", ["Standing close to teammates", "Marking the same opponent as another player", "Spreading out and creating passing lanes", "Bunching near the goal"], 2),
    ("A player notices that the defender is watching intently and appears poised to intercept the next pass during a competitive basketball game. What is the best course of action for the player to keep possession and set up a goal?", ["Dribble faster", "Hold the ball, and dribble", "Fake a pass, then redirect", "Yell at the defender"], 2),
    ("A student creates a personal fitness program that incorporates jogging for aerobic conditioning and push-ups for anaerobic training after learning about various exercise types. Which fitness principle is being used by the student?", ["Skill improvisation", "Excessive physical or mental strain", "Balanced training components", "Isolation method"], 2),
    ("A soccer coach observes a player's poor kicking technique during practice and wishes to give immediate feedback for improvement. Which approach is best in this case to find and fix the issue right away?", ["Post-game review", "Peer questionnaire", "Real-time teacher observation", "Reaction time test"], 2),
    ("In a sprint training session, a student stands at the starting line. When the coach blows the whistle, the student takes off with explosive speed. What specific skill is the student using in this situation?", ["Muscular endurance", "Reaction time", "Flexibility", "Balance"], 1),
    ("A student looks over their observation notes and examines video footage after watching a classmate perform during a fitness drill to create a customized training program that focuses on particular areas that need work. What ability is displayed?", ["Reaction testing", "Strength evaluation", "Evaluating individual performance relative to peer group", "Designing a feedback-based improvement plan"], 3),
    ("A badminton player lunges forward to return a drop shot during a game, then quickly straightens out to get ready for the next shot. Which aspect of fitness related to skills is most prominently displayed here?", ["Speed", "Coordination", "Endurance", "Balance"], 3),
    ("In a Physical Education lesson, the instructor plays two video clips of various tennis serve styles, one with obvious flaws and the other with correct technique. To determine which serve is more effective and why, students are asked to compare the serves and point out significant variations in grip, stance, and follow-through. What do students practice?", ["Performance comparison and analysis", "Estimation method for uncertain outcomes", "Speed drills", "Object manipulation"], 0),
    ("A student is required to choreograph a distinctive routine that combines jumping, twisting, and stretching to convey a selected theme after learning different movement patterns in class. What kind of thinking is he doing?", ["Copying a known routine", "Repeating familiar movement skill sets", "Creating a movement combination", "Recalling a lesson"], 2),
    ("Which law established the K to 12 Basic Education Program in the Philippines?", ["Republic Act 10533", "Republic Act 10912", "Republic Act 10687", "Republic Act 10524"], 0),
    ("The Physical Education instructor gives the students a rubric that emphasizes important skills like hand control, posture, and dribbling consistency during a basketball skills training session. A student starts practicing dribbling drills after going over the rubric, modifying their motions to meet the specified standards. Which skill is being used?", ["Self-motivation", "Student-to-Student Performance Assessment", "Rubric-based improvement", "Reaction time"], 2),
    ("A Physical Education teacher watches a video of a basketball skills class and notes that many students had trouble with proper footwork during lay-up drills. Which of the following best illustrates the teacher's successful application of reflective practice?", ["Planning drills that target observed skill gaps in the next session", "Uploading the video to a school platform without feedback", "Ignoring the video and teaching the same way next time", "Asking students to teach the next class"], 0),
    ("A player gets possession of the ball close to the opponent's goal during a fiercely contested soccer match. The player finds a teammate in a better position and makes a precise pass that results in a goal as a defender rapidly closes in, saving him from trying a risky shot. This decision is an obvious example of?", ["Delay tactic", "Tactical awareness", "Defensive strategy", "Mindless execution"], 1),
    ("A student modifies their stance, grip, and aim to hit the bullseye consistently during an archery exercise in Physical Education class. Which fitness skill is the student primarily exhibiting?", ["Agility", "Power", "Accuracy", "Balance"], 2),
    ("After watching a slow-motion replay of her vault performance, a gymnast spots a mistake in her takeoff technique. She changes her movement for her next attempt. What skill is she using?", ["Identifying errors only", "Passive watching", "Video-assisted correction", "Self-pacing"], 2),
    ("A student observes that his serve frequently goes outside the court lines during a competitive volleyball match. He starts modifying his hand placement and aims according to the ball's previous landing spot to get better. What kind of application of skills is this?", ["Random guessing", "Constructive peer performance feedback", "Real-time performance evaluation", "Muscle Strength Competition"], 2),
    ("A student finds it difficult to stay balanced and aligned during a gymnastic pose in Physical Education class. After giving it some thought, he realized that his bad posture is a result of weak core muscles. What kind of analysis is the student exhibiting?", ["Observation without reasoning", "Muscle strength evaluation and assessment", "Cause-and-effect reasoning in performance", "Scoring accuracy"], 2),
    ("A student jogs around the track while wearing a heart rate monitor during Physical Education class. To make sure their heart rate remains within the desired range for aerobic conditioning, they frequently check the device. Which idea is the student using?", ["Skill analysis", "Manipulative tracking", "Exercise intensity monitoring", "Enhanced sense of body control"], 2),
    ("A teacher observes that a number of students find endurance exercises difficult during Physical Education class. In order to address this, the instructor establishes clear goals for each student's improvement in cardio fitness, such as extending the beep test duration over a period of four weeks. In this case, what kind of assessment tool is the instructor using?", ["Broad outcomes", "SMART goals", "General plan", "Peer review"], 1),
    ("A Physical Education teacher reviews the fitness post-assessment results and finds that although the majority of students have met their personal fitness objectives, there have been a number of reported cases of poor sportsmanship, including arguments during games and a lack of team spirit. What should be the primary focus of the upcoming lesson plan to close this gap?", ["More competitive games", "Physical drills and training activity", "Shorter class periods", "Character education and fair play"], 3),
    ("A dancer adjusts their steps and spacing during a live performance on a stage that is smaller than usual to prevent collisions and preserve flow. What ability is being displayed?", ["Enhancement of physical performance memory", "Spatial awareness application", "Flexibility", "Endurance training"], 1),
    ("A Zumba routine is being practiced by a group of students in a Physical Education class. As they execute moves like grapevines, claps, and turns, their teacher stresses the value of maintaining rhythm with the music. \"Why do we need to follow the beat and move in sync?\" a student asks. how can coordination be enhanced by rhythmic exercises like this one?", ["By improving endurance only", "By repeating exact steps without music", "By promoting and supporting slower, more deliberate and mindful physical movements.", "By synchronizing movements to beats, enhancing timing and balance"], 3),
    ("In a dance performance task in class, a student carefully arranges their arm and foot movements according to the beat and rhythm of the music to perform a choreographed routine. What skill is being shown?", ["Improvisation", "Complex movement planning", "Simple fitness testing", "Evaluation through performance-based feedback"], 1),
    ("Basketball players must coordinate their movements during a defensive zone rotation as part of a training exercise. To keep coverage and prevent gaps, they anticipate one another's movements. Which concept of movement are they using?", ["Force", "Space awareness", "Relationship", "Timing"], 2),
    ("A student chooses to record his performance and closely examines his foot placement and body mechanics to pinpoint potential error sources after multiple example of unsuccessful lay up attempts during basketball practice. This action is the best?", ["regression", "self-blame", "diagnostic action", "competitive behavior"], 2),
    ("One of the students' assignments in Physical Education is to work on their volleyball serving technique. After every try, the instructor asks the student to use the resources in the classroom to assess their performance. Which approach is the most suitable and practical for the student to employ at the moment?", ["Self-assessment checklist", "Virtual simulation", "Motion sensors checklist", "Performance app"], 0),
    ("A student decides to make a weekly fitness plan after realizing they feel lethargic during the day. They consist of strength training on Tuesdays and Thursdays, jogging on Mondays and Wednesdays, and flexibility-boosting yoga sessions on Fridays. Which fitness principle is being used by the student?", ["Analyzing individual body composition level", "Specificity and balance", "Overtraining", "Nutrition Control"], 1),
    ("Ana gets ready to spike the ball during a volleyball match. She takes a few steps forward with her lead foot, then turns her hips and torso before swinging her hitting arm quickly. The coach commends her for employing proper body mechanics to produce strong force. Which biomechanics principle is Ana using to generate the most force possible during her movement?", ["Linear stability", "Sequential force summation", "Static balance", "Symmetry of motion and power"], 1),
    ("A student with a hearing impairment participates in a circuit training exercise during Physical Education class. The instructor uses hand signals to direct the student as they move between stations and makes sure that all exercise instructions are demonstrated visually.", ["Verbal cueing", "Exclusion rooted in visual communication barriers", "Universal Design for Learning", "Kinesthetic grading"], 2),
    ("A student gets their Body Mass Index (BMI) result and decides to cut back on sugary snacks while eating more vegetables to reach a healthier weight. What idea is the student using in this situation?", ["Muscle development", "Fitness theory", "Flexibility measurement", "Body composition data"], 3),
    ("A teacher observes that very few students are actively participating in a volleyball unit. What should a Physical Education teacher do first when implementing reflective practice to increase student engagement?", ["Grade students based on participation and penalize inactivity.", "Document student interactions and engagement levels.", "Eliminate the volleyball unit from the curriculum.", "Ask another teacher to conduct the class for better results."], 1),
    ("A teacher observes that one student has restricted mobility and finds it difficult to execute the standard overhand throwing technique used in a team game during physical education class. the instructor modifies the task by permitting the student to participate in the group while using a chest pass from a seated position. Why probably did the instructor make this change?", ["Enhance it further to ensure greater competitiveness and better overall performance", "To make it more fun", "To promote inclusion and equal participation", "To reduce grading time"], 2),
    ("A student decides to switch to high-intensity interval training (HIIT) for better results after regularly examining his fitness tracker data and finding little improvement in heart rate. What is he engaged in?", ["Evaluating fitness effectiveness", "Committing routine steps to memory", "Testing others", "Choosing random activities"], 0),
    ("A PE student extensively uses a self-assessment checklist to track their progress in mastering different sports skills each week. What does this practice show?", ["Creating feedback tools", "Applying self-monitoring", "Guessing progress", "Conducting a test"], 1),
    ("The teacher notices that several students are having difficulty keeping up with the high-intensity aerobic routine during Physical Education class. To better accommodate the students' present fitness levels, she adjusts the activity by shortening its duration and making the movements simpler. In this case, which fitness principle is the instructor using?", ["Summative evaluation", "Aligning content, standards, instruction, and assessment effectively", "Developmentally appropriate instruction", "Competitive strategy"], 2),
    ("To assist students in analyzing body mechanics and honing their technique, a teacher records two distinct serves during a tennis lesson and replays them in slow motion. In this case, what kind of teaching tool is being used?", ["Fitness tracker", "Video analysis", "Stopwatch", "Peer scoring"], 1),
    ("A hurdler always leans forward right after landing from each jump in a 110-meter hurdle race. During quick changes, this method aids the athlete in regaining momentum and keeping their balance. Which biomechanical principle is best demonstrated by this action?", ["Center of gravity", "Law of inertia", "Base of support", "Counterbalance"], 0),
    ("What does UDL stand for in educational program design?", ["United Development Learning", "Universal Design for Learning", "Unique Differentiated Learning", "Uniform Design Logic"], 1),
    ("Which situation best exemplifies how energy and effort are used when moving during a sporting activity?", ["A player sitting on the bench", "A dancer stretching before the music was set and played", "A runner jogging at a slow pace, then sprinting to the finish", "A student reading about sports"], 2),
    ("A play is signaled by the coach during a basketball game, and the point guard promptly communicates it to the teammates through hand and verbal cues. Why is this type of communication crucial to the successful implementation of team strategies?", ["It increases noise.", "It aligns actions toward a goal.", "It shows off skills.", "It adds pressure and challenges."], 1),
    ("Why is curriculum content analysis important in PE and Health Education?", ["To update textbooks", "Increase the frequency of administering tests regularly.", "To ensure age-appropriate learning competencies", "To lower class hours"], 2),
    ("A teacher observes that several students have trouble understanding spoken instructions because of language barriers during Physical Education class. The instructor uses gestures to illustrate activities and incorporates visual aids like diagrams to address this. The pupils can thus engage in the lesson efficiently. What method of instruction is the instructor using to meet the various needs of the students?", ["Peer learning", "Cognitive overload", "Exclusion based on lack of skills.", "Universal Design for Learning"], 3),
    ("A teacher is evaluating the students' performance in the long jump exercise during a Physical Education class. Instead of depending only on anecdotal records, the instructor chooses to use a rubric. Why is evaluating students' long jump performance with a rubric a better option?", ["They require less effort.", "They provide qualitative stories.", "They use standardized scoring.", "They are easier to forget."], 2),
    ("A student assesses a classmate's movement by providing detailed feedback on how to enhance arm swing and leg lift coordination for more fluid execution after watching the student engaged in a skipping drill during Physical Education class. What is the student engaged in?", ["Evaluating performance effectiveness", "Technique based on uncertain prediction", "Practice non-locomotor skills", "Guessing skill type"], 0),
    ("A teacher uses a rubric to evaluate a student's volleyball serve in a Physical Education class. What is happening in this situation?", ["Coordination check", "Performance evaluation tool", "Warm-up preparation before physical activity", "Memory recall"], 1),
    ("A teacher evaluates students during a cooperative game in Physical Education class using a performance-based rubric. The findings show that a large number of students struggle with communication and teamwork. What is the best course of action for the instructor to deal with this problem?", ["Introduce structured team-building games", "Grade harshly to enforce discipline and strictness", "Increase solo drills", "Decrease time in group activities"], 0),

    # --- Section 3 (Q101 to Q150) ---
    ("The team gets together in the locker room to watch a video of their performance after losing a close game. They talk about ways to prevent the same errors in the following game as they examine lost passes, turnovers, and bad positioning. In this scenario, what skill are they honing?", ["Memory games", "Tactical training", "Dynamic coordination skill-building exercises", "Game analysis and error recognition"], 3),
    ("A student examines his monthly fitness log and determines the need to up the ante on his cardio exercises after observing a plateau in their endurance. He consequently incorporates interval running into his training regimen. What ability or conduct is the student exhibiting?", ["Deliberate act of evading responsibility", "Tracking and adjustment", "Grading", "Performance testing"], 1),
    ("A child is instructed to pass the ball to a teammate who is a few meters away during Physical Education class. To deliver the ball accurately, the child tosses it with both hands from above the head. In this case, what skill is the child using?", ["Power lifting", "Jumping drills", "Overhand throwing (manipulative)", "Skipping movement and coordination techniques"], 2),
    ("Increasing student motivation during fitness activities is a professional objective for a Physical Education teacher. The teacher wants to know if students are getting more involved after introducing a new program that incorporates both individual and group goals. Which approach best illustrates how the instructor is using reflective practice to track students' progress toward this objective?", ["Comparing students' fitness levels from different schools", "Student effort tracked with weekly checklist.", "Giving more rewards to top-performing athletes", "Increasing the difficulty of all workouts to push students harder"], 1),
    ("Following a series of basketball drills, students are given the task of creating their own scoring rubric to assess their dribbling skills during a mini-tournament. Which cognitive ability are they expected to exhibit?", ["Follow pre-made tools", "Judge randomly", "Develop evaluation criteria", "Pointless scoring without intent"], 2),
    ("A student is captured on camera swimming 50 meters during a Physical Education lesson. The student modifies their arm swing and running posture to increase speed and efficiency on their subsequent try after watching the video and getting teacher feedback. In this case, what is being applied?", ["Emotional feedback", "Mental imagery and visualization technique", "Scoring criteria", "Skill correction through analysis"], 3),
    ("What is the main goal of reflective practice in teaching?", ["To monitor student discipline", "To improve teaching and personal effectiveness", "To track school finances", "To replace formal evaluation"], 1),
    ("A defender keeps a close eye on the offensive player's movements during a basketball game. The defender immediately moves to anticipate a drive in the left direction when the opponent quietly turns their shoulders and looks to the left. In this situation, what cognitive ability is the defender using?", ["Disregard", "Pattern blindness", "Reflex confusion", "Situational awareness"], 3),
    ("A wing defender observes the goal attack of the other team getting ready for a fast pass during a competitive netball match. The defender moves into position instinctively and stops the ball as it crosses into the passing lane. Which aspect of fitness related to skills is best illustrated in this situation?", ["Power", "Balance", "Reaction time", "Coordination"], 2),
    ("A student watches a classmate's jump shot during a basketball skills evaluation in Physical Education class and provides feedback based on the arm extension and wrist flick following the release. Which skill is being used by the student?", ["Quickness in response to stimuli", "Critical element identification", "Static balance", "Strength analysis"], 1),
    ("A teacher adapts a classic game of tag in a Physical Education class by creating rest areas, utilizing slower-paced movement options like walking, and designating roles like “tag assistant” for students who are less comfortable running. In what way does this modification encourage inclusive sports participation?", ["Makes rules easier to follow", "Ensures some students always win and enjoyed the activity", "Allows participation regardless of ability", "Decreases competition"], 2),
    ("Which type of assessment is conducted at the end of a unit?", ["Formative", "Diagnostic", "Summative", "Pre-assessment"], 2),
    ("Students are asked to use video playback tools to evaluate a recorded volleyball serve performance during a Physical Education lesson. What is the student's primary duty during this activity?", ["Ignore slow-motion replay.", "Note biomechanical flaws.", "Focus on crowd reactions.", "Remove peer involvement."], 1),
    ("In a Physical Education basketball skills test, your teacher gives you the task of assessing a classmate's jump shot using a performance rubric that covers elements like consistency, balance, shooting form, and follow-through. What should be the first step in effectively using the rubric to guarantee a fair and accurate evaluation?", ["Ask the coach for help.", "Apply each performance criterion objectively.", "Score based on overall impression and critic.", "Record it without watching."], 1),
    ("Following the implementation of a two-week basketball dribbling drill program, a Physical Education teacher compares each student's dribbling accuracy and control before and after the practice sessions by reviewing video footage and performance checklists. What does this illustrate?", ["Skill application", "Baseline memorization", "Progress evaluation", "Routine development"], 2),
    ("A group of Physical Education teachers is entrusted with bringing their program into compliance with national standards during a curriculum review meeting. They observe that while some elements of their current curriculum place a strong emphasis on competition and training elite athletes, other elements place more emphasis on traditional games and unstructured play. Which of the following best describes how the school's Physical Education curriculum deviates from the national objectives for inclusive and comprehensive Physical Education?", ["Focus only on competitive sports", "Emphasis on lifelong fitness", "Use of varied assessments", "Promotion of inclusive practices"], 0),
    ("Using one hand to bounce the ball repeatedly, Marco deftly moves it down the court during a basketball game. Which kind of basic motor skill is demonstrated by this action?", ["Locomotor", "Manipulative", "Non-locomotor", "Rhythmic"], 1),
    ("Two regional Physical Education (PE) programs are showcased at a national PE conference. Physical fitness, skill development, and social-emotional learning (SEL) elements like self-awareness and teamwork exercises are all part of Region A's curriculum. However, the curriculum in Region B places no or little emphasis on SEL and instead emphasizes motor skills and fitness. What does this likely tell about the PE programs in Regions A and B?", ["Better focus on physical skills", "A gap in holistic education", "Stronger competitive edge", "Enhanced skill testing"], 1),
    ("Administrators observed during a school-wide review of Physical Education (PE) results that while students are proficient in fundamental sports skills, many have trouble collaborating with others, setting goals, and putting fitness concepts into practice outside of PE class. Teachers also noted low student participation in wellness classes covering subjects like nutrition and stress reduction. Based on the scenario, which of the following is a weakness in the current Physical Education curriculum?", ["Repetition of fitness tests in Grades 7 and 8", "Integration of comprehensive health education modules", "Integration of dance and sports", "Well-distributed assessment tools"], 1),
    ("A group of students observes their peers doing a jump rope routine during Physical Education class. They observe and score particular criteria like timing, rhythm, and form using peer assessment forms. Which skill are the pupils honing?", ["Peer observation and feedback", "Monitoring progress in flexibility training", "Rule enforcement", "Rhythm creation"], 0),
    ("A player abruptly changes course to evade a defender while keeping control and balance during a fast-paced soccer match. Which aspect of fitness related to skills is most prominently displayed here?", ["Power", "Flexibility", "Strength", "Agility"], 3),
    ("A teacher in a Physical Education class adapts a classic game of tag by creating rest areas, utilizing slower-paced movement options like walking, and designating roles like \"tag assistant\" for students who are less comfortable running. In what way does this modification encourage inclusive involvement in athletics?", ["Locomotor and space awareness", "Manipulative and force", "Non-locomotor and rhythm", "Rhythmic and energy use is needed"], 0),
    ("During a gymnastics unit in PE class, the teacher performs a short routine on a balance beam, emphasizing steady posture and core control. After watching, the students are asked to observe and point out moments where the teacher demonstrated strong balance and proper body alignment. What skill are the students applying in this activity?", ["Observation techniques", "Quickness in responding to stimuli", "Flexibility drills", "Nutrition planning"], 0),
    ("The teacher wants to accommodate students with a range of physical and cognitive abilities in a Physical Education class that focuses on a basketball dribbling exercise. Which of the following instructional approaches most closely adheres to the Universal Design for Learning (UDL) tenets?", ["Option 1", "Delivering instructions only verbally", "Using only physical demonstrations", "Multiple ways to perform tasks"], 3),
    ("Maria is learning the overhand serve in volleyball during a Physical Education lesson. Her teacher gives the class instructions to evaluate their own performance following a practice round. Which self-assessment technique would be best for Maria to determine how well she performed the skill?", ["Watching a professional game in volleyball", "Reflecting using performance criteria", "Asking friends to cheer", "Memorizing rules"], 1),
    ("A coach observes that a student frequently loses possession of the ball while dribbling during basketball practice. Which technique should the coach suggest to help the student get better at controlling the ball and coordinating?", ["Watching the ball constantly moving and rolling", "Keeping legs straight", "Using finger pads and lowering stance", "Holding the ball with both hands"], 2),
    ("A player in the front row of a fierce volleyball match observes that the blockers on the other team are constantly positioned to deflect strong spikes. The player aims for an open area on the opposing team's court by gently tipping the ball over the blockers rather than forcing a spike. Which of the following best sums up the player's ability in this scenario?", ["Avoidance", "Strategic adjustment", "Lack of power and speed", "Panic play"], 1),
    ("Anna records her time for the 50-meter freestyle during swim practice and observes that she routinely finishes in 36.5 seconds. Then, by modifying her breathing technique and practicing every day, she sets a goal to cut her time to 36.0 seconds in three weeks. Which principle does Anna's method best illustrate?", ["Subjective analysis", "SMART goal setting", "Delayed gratification", "Static routine"], 1),
    ("A student is asked to make a customized improvement plan during a Physical Education lesson that focuses on improving table tennis skills. The student wants to participate in intramural competitions next month but finds it difficult to make backhand returns. Which of the following should be the student's top priority in his plan, according to the individualized training principle?", ["Player weaknesses and goals", "Peer preferences", "Coach convenience", "Only strength areas and weaknesses"], 0),
    ("The other team starts a fast break in a high-stakes basketball game, accelerating the pace to score points as soon as possible. The coach responds by telling the team to switch to a zone defense formation. This modification aids in covering ground and successfully containing the players who are advancing. Which strategy is the team using?", ["Offensive drill", "Passive play and drill", "Strategic slowing", "Defensive reorganization"], 3),
    ("A student performs a handstand on the mat during a Physical Education class gymnastics demonstration and maintains the pose for a number of seconds. Her coach emphasizes how she controls her body without shifting or falling. Which skill-related aspect of fitness is most prominently displayed in this activity?", ["Balance", "Reaction time", "Agility", "Speed"], 0),
    ("How does differentiated instruction support learners in PE?", ["By making all students do the same activity", "By adjusting tasks based on readiness and interests", "By reducing physical activity", "By removing grading"], 1),
    ("A Physical Education teacher finds that half of the class does not comprehend the idea of heart rate zones during aerobic activities after performing a fitness assessment. What is the best course of action for the instructor to deal with this problem?", ["Move on to the next topic and physical activities", "Re-teach using interactive methods", "Assign textbook reading", "Ignore the results to avoid delay"], 1),
    ("The Physical Education teacher modifies the curriculum to include more agility drills and movement coordination exercises that are suited to the needs of the students after a pre-test indicates that the majority of the students have poor coordination. Which assessment practice is best illustrated by this scenario?", ["Summative grading", "Data-driven instruction", "Norm-referenced testing", "Psychometric analysis"], 1),
    ("When playing tag in Physical Education class, a teacher asks students to evaluate various movement patterns, like side shuffling, sprinting, or pivoting, and choose the one that works best for avoiding a defender who is moving quickly. Which skill are they honing?", ["Running faster", "Counting steps", "Imitating or replicating a skill", "Evaluating movement options"], 3),
    ("A student looks at a BMI chart to determine their physical condition after noticing a drop in their energy levels during Physical Education class. The student establishes particular health objectives to raise their general level of fitness based on the findings. Which idea is being used?", ["Endurance tracking", "Body composition interpretation", "Reaction time skill assessment", "Static balance"], 1),
    ("What is the primary purpose of diagnostic assessment in program planning?", ["Process of giving academic scores", "To end a program", "To report to parents", "Identify student strengths and needs"], 3),
    ("A soccer player uses dribbling to get past defenders. They pass to teammates to set up scoring chances, and they shoot accurately to try for a goal. What does this show?", ["Understanding of body movement mechanics", "Application of combined motor skills", "Memorization of rules", "Reaction time testing"], 1),
    ("The teacher watches students in a Physical Education class engage in a dribbling activity with varying skill levels. The teacher pairs a student who regularly exhibits advanced dribbling skills with another who finds it difficult to maintain ball control to help all of the students get better. The less-talented student gradually starts to make progress.", ["Cooperative grouping", "Elimination method", "Uniform instruction", "Peer grading"], 0),
    ("A student does a series of bending and stretching exercises to improve joint flexibility and release tense muscles before their Physical Education class starts. What does this application aim to accomplish?", ["Muscle overload", "Cardio exercise", "Dynamic warm-up", "Power development"], 2),
    ("Coach Rivera examines each student's medical records prior to starting a new school-wide fitness program to make sure the exercises are suitable for their limitations and physical state. In this case, what kind of evaluation is Coach Rivera using?", ["Summative", "Diagnostic", "Peer", "Reflective"], 1),
    ("A teacher in a Physical Education class observes that the majority of students received low scores on the flexibility section of their fitness test. In response, the instructor modifies the warm-up to incorporate yoga poses and dynamic stretching to focus on increasing flexibility. This practice is best described as:", ["Ignoring feedback", "Curriculum design", "Peer collaboration", "Data-driven instruction"], 3),
    ("A dancer discovers during a dance performance practice that spinning at a fast pace causes her spins to become unsteady. She examines her technique and finds that her spotting and core engagement are not consistent. What is she evaluating about her performance?", ["Quick response to an external stimulus", "Relationship between speed and balance", "Object control", "Fitness level"], 1),
    ("Agility ladder drills are part of a varsity athlete's weekly training regimen. Every session, the athlete logs his 10-meter sprint time and reaction to whistle cues to see if these drills are having an effect. The athlete observes a quicker change of direction and a quicker reaction time after three weeks. Which procedure is the athlete using?", ["Peer validation and monitoring", "Baseline denial", "Performance monitoring", "Result ignoring"], 2),
    ("During a field day activity, a student aims and throws a Frisbee at a cone 10 meters away. They change their grip and throwing motion based on the wind direction and distance. What basic movement pattern is mainly shown?", ["Running", "Bending", "Throwing", "Jumping"], 2),
    ("A PE teacher notices that a student finds it difficult to stay balanced during beam routines during a gymnastics class. The student also acknowledges feeling unsteady in different positions after the session. What should be done next to help the student perform better?", ["Focus on speed drills and endurance", "Avoid the activity", "Practice static poses and core stability", "Run longer distances"], 2),
    ("What does the 'R' in SMART goals represent?", ["Relevant", "Realistic", "Reasonable", "Refined"], 0),
    ("A student observes that their classmates' knees are crossing their toes when performing squats during Physical Education class, which may cause harm. To improve posture, the student goes over and recommends keeping the knees in line with the ankles and keeping the back straight. What ability is the pupil displaying?", ["Flexibility drills", "Constructive peer feedback", "Tracking and adjusting personal behavior", "Muscle testing"], 1),
    ("A student has already learned the fundamentals of floating and kicking during a swimming lesson. The coach asks the student to concentrate on honing their kicking technique across the shallow end after taking away the floating board. As a result of the coach's feedback, the student now makes fewer mistakes and modifies their movements. Which motor learning stage is the student in?", ["Learning to kick correctly without floating devices", "Only observing others without participating limits personal growth and understanding.", "Repeating random movements", "Memorizing rules"], 0),
    ("Students watch a video playback of their performance after finishing a dance routine in class. After assessing their timing, posture, and coordination, they make a note of the precise areas they need to work on for the following practice. Which ability are the pupils displaying?", ["Goal setting", "Self-evaluation through analysis", "Self-assessment of personal performance", "Participating in a competition"], 1)
]

os.makedirs('lib/data/bped_ppst_drill_9', exist_ok=True)

def generate_section(sec_id, start_idx, end_idx):
    sec_items = raw_items[start_idx:end_idx]
    code = f"import '../../models/question.dart';\n\n"
    code += f"const List<Question> bpedPpstDrill9Section{sec_id}Questions = [\n"
    
    for local_idx, (q_text, opts, corr_idx) in enumerate(sec_items):
        q_id = start_idx + local_idx + 1
        opts_formatted = ",\n      ".join([repr(o) for o in opts])
        code += f"  Question(\n"
        code += f"    id: {q_id},\n"
        code += f"    questionText:\n        {repr(q_text)},\n"
        code += f"    options: [\n      {opts_formatted},\n    ],\n"
        code += f"    correctAnswerIndex: {corr_idx},\n"
        code += f"  ),\n"
        
    code += "];\n"
    
    file_path = f"lib/data/bped_ppst_drill_9/bped_ppst_drill_9_section_{sec_id}.dart"
    with open(file_path, "w") as f:
        f.write(code)
    print(f"Generated {file_path} with {len(sec_items)} items.")

generate_section(1, 0, 50)
generate_section(2, 50, 100)
generate_section(3, 100, 150)

print("All 3 BPED PPST Drill 9 section files successfully generated!")
